apiVersion: core.humio.com/v1alpha1
kind: HumioCluster
metadata:
  creationTimestamp: "2025-02-20T00:01:40Z"
  generation: 38
  name: rafael-eks-cluster
  namespace: logging
  resourceVersion: "10438982"
  uid: 0bb549e3-ad49-4156-9332-414d07e5b599
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
          - key: k8s-app
            operator: In
            values:
            - logscale
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - humio
        topologyKey: kubernetes.io/hostname
  autoRebalancePartitions: true
  dataVolumePersistentVolumeClaimSpecTemplate:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5800Gi
    storageClassName: gp2
  digestPartitionsCount: 840
  disableInitContainer: false
  environmentVariables:
  - name: S3_STORAGE_BUCKET
    value: rafael-eks-cluster
  - name: S3_STORAGE_REGION
    value: us-west-2
    valueFrom:
      secretKeyRef:
        key: server-secret
        name: postmark
  - name: BUCKET_STORAGE_MULTIPLE_ENDPOINTS
    value: "true"
  - name: S3_STORAGE_ENCRYPTION_KEY
    value: us-west-2
    valueFrom:
      secretKeyRef:
        key: s3-storage-encryption-key
        name: rafael-eks-cluster-s3-storage-encryption
  - name: USING_EPHEMERAL_DISKS
    value: "true"
  - name: LOCAL_STORAGE_PERCENTAGE
    value: "80"
    valueFrom:
      secretKeyRef:
        key: s3-storage-encryption-key
        name: rafael-eks-cluster-s3-storage-encryption
  - name: S3_STORAGE_PREFERRED_COPY_SOURCE
    value: "true"
  - name: LOCAL_STORAGE_MIN_AGE_DAYS
    value: "7"
  - name: ZOOKEEPER_URL
    value: z-1.mskclusterrafaeleksclu.808cuv.c8.kafka.us-west-2.amazonaws.com:2181,z-2.mskclusterrafaeleksclu.808cuv.c8.kafka.us-west-2.amazonaws.com:2181,z-3.mskclusterrafaeleksclu.808cuv.c8.kafka.us-west-2.amazonaws.com:2181
  - name: KAFKA_SERVERS
    value: b-1.mskclusterrafaeleksclu.808cuv.c8.kafka.us-west-2.amazonaws.com:9094,b-2.mskclusterrafaeleksclu.808cuv.c8.kafka.us-west-2.amazonaws.com:9094,b-5.mskclusterrafaeleksclu.808cuv.c8.kafka.us-west-2.amazonaws.com:9094
  - name: SINGLE_USER_USERNAME
    value: admin
  - name: ENABLE_SCHEDULED_REPORT
    value: "true"
  - name: DEFAULT_PDF_RENDER_SERVICE_URL
    value: http://pdf-render-service.logging.svc.cluster.local:5123
  - name: POSTMARK_FROM
    value: Humio <noreply@humio.com>
  - name: POSTMARK_SERVER_SECRET
    valueFrom:
      secretKeyRef:
        key: server-secret
        name: postmark
  - name: HUMIO_DEBUG_LOG_LEVEL
    value: debug
  - name: HUMIO_DEBUG_LOG_ADDRESS
    value: awstest.mi-arch-aws-logscale.humio.net
  - name: HUMIO_DEBUG_LOG_TOKEN
    value: 5421e9b3-3286-4b63-b465-fb6415344aa9
  - name: PUBLIC_URL
    value: https://awstest.mi-arch-aws-logscale.humio.net/
  - name: SINGLE_USER_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: rafael-eks-cluster-single-user-password
  extraKafkaConfigs: security.protocol=SSL
  hostname: awstest.mi-arch-aws-logscale.humio.net
  humioServiceAccountAnnotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::471112840547:role/logscale-rafael-eks-cluster
  image: humio/humio-core:1.171.1
  license:
    secretKeyRef:
      key: humio-license-key
      name: rafael-eks-cluster-license
  nodeCount: 9
  priorityClassName: ""
  resources:
    limits:
      cpu: 7
      memory: 28Gi
    requests:
      cpu: 7
      memory: 28Gi
  targetReplicationFactor: 2
  tls:
    enabled: true
status:
  licenseStatus:
    expiration: 2025-07-14 08:39:03 +0000 UTC
    type: onprem
  message: 'unable to create pod: Pod "rafael-eks-cluster-core-gtdbew" is invalid:
    [spec.containers[0].env[1].valueFrom: Invalid value: "": may not be specified
    when `value` is not empty, spec.containers[0].env[3].valueFrom: Invalid value:
    "": may not be specified when `value` is not empty, spec.containers[0].env[5].valueFrom:
    Invalid value: "": may not be specified when `value` is not empty]'
  nodePoolStatus:
  - desiredBootstrapTokenHash: e1e3a10cf43c214f9d372e2d1f99eacca4f506d4738cee20f37fd1b0d03195ba
    desiredPodHash: 38bf54067194a64244a3f76c55b930963b651761d073a9be615f79243974e66b
    desiredPodRevision: 39
    name: rafael-eks-cluster
    state: Restarting
  observedGeneration: "38"
  state: Restarting
  version: 1.171.1--build-2704--sha-776defa824f41d0f226f711e744398e89b9e2604
