{{- if .Values.operator.rbac.create -}}
{{- if .Values.operator.rbac.createServiceAccount -}}
{{- $commonLabels := include "humio.labels" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Release.Name }}'
  namespace: '{{ default "default" .Release.Namespace }}'
  labels:
    {{- $commonLabels | nindent 4 }}
{{- end }}
{{- end }}
