# permissions for end users to view humiogroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humiogroup-viewer-role
rules:
- apiGroups:
  - core.humio.com
  resources:
  - humiogroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.humio.com
  resources:
  - humiogroups/status
  verbs:
  - get
