# permissions for end users to view humioviews.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humioview-viewer-role
rules:
- apiGroups:
  - core.humio.com
  resources:
  - humioviews
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.humio.com
  resources:
  - humioviews/status
  verbs:
  - get
