# permissions for end users to view humioexternalclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humioexternalcluster-viewer-role
rules:
- apiGroups:
  - core.humio.com
  resources:
  - humioexternalclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.humio.com
  resources:
  - humioexternalclusters/status
  verbs:
  - get
