# permissions for end users to edit humiofilteralerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humiofilteralert-editor-role
rules:
- apiGroups:
  - core.humio.com
  resources:
  - humiofilteralerts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.humio.com
  resources:
  - humiofilteralerts/status
  verbs:
  - get
