# permissions for end users to edit humiorepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humiorepository-editor-role
rules:
- apiGroups:
  - core.humio.com
  resources:
  - humiorepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.humio.com
  resources:
  - humiorepositories/status
  verbs:
  - get
