# permissions for end users to view humiofilteralerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humiofilteralert-viewer-role
rules:
- apiGroups:
  - core.humio.com
  resources:
  - humiofilteralerts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.humio.com
  resources:
  - humiofilteralerts/status
  verbs:
  - get
