# permissions for end users to edit humioscheduledsearches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humioscheduledsearch-editor-role
rules:
- apiGroups:
  - core.humio.com
  resources:
  - humioscheduledsearches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.humio.com
  resources:
  - humioscheduledsearches/status
  verbs:
  - get
