# permissions for end users to edit humioclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humiocluster-editor-role
rules:
- apiGroups:
  - core.humio.com
  resources:
  - humioclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.humio.com
  resources:
  - humioclusters/status
  verbs:
  - get
