# permissions for end users to edit humioparsers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humioparser-editor-role
rules:
- apiGroups:
  - core.humio.com
  resources:
  - humioparsers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.humio.com
  resources:
  - humioparsers/status
  verbs:
  - get
