# permissions for end users to view humiorepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humiorepository-viewer-role
rules:
- apiGroups:
  - core.humio.com
  resources:
  - humiorepositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.humio.com
  resources:
  - humiorepositories/status
  verbs:
  - get
