# permissions for end users to edit humioactions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humioaction-editor-role
rules:
- apiGroups:
  - core.humio.com
  resources:
  - humioactions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.humio.com
  resources:
  - humioactions/status
  verbs:
  - get
