# permissions for end users to edit humioroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: humiorole-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: humio-operator
    app.kubernetes.io/part-of: humio-operator
    app.kubernetes.io/managed-by: kustomize
  name: humiorole-editor-role
rules:
- apiGroups:
  - core.humio.com
  resources:
  - humioroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.humio.com
  resources:
  - humioroles/status
  verbs:
  - get
