# permissions for end users to view humioalerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humioalert-viewer-role
rules:
- apiGroups:
  - core.humio.com
  resources:
  - humioalerts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.humio.com
  resources:
  - humioalerts/status
  verbs:
  - get
