# permissions for end users to view humioclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humiocluster-viewer-role
rules:
- apiGroups:
  - core.humio.com
  resources:
  - humioclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.humio.com
  resources:
  - humioclusters/status
  verbs:
  - get
