# permissions for end users to edit humioalerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humioalert-editor-role
rules:
- apiGroups:
  - core.humio.com
  resources:
  - humioalerts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.humio.com
  resources:
  - humioalerts/status
  verbs:
  - get
