# permissions for end users to view humiofeatureflags.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humiofeatureflag-viewer-role
rules:
- apiGroups:
  - core.humio.com
  resources:
  - humiofeatureflags
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.humio.com
  resources:
  - humiofeatureflags/status
  verbs:
  - get
