# permissions for end users to view humioscheduledsearches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humioscheduledsearch-viewer-role
rules:
- apiGroups:
  - core.humio.com
  resources:
  - humioscheduledsearches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.humio.com
  resources:
  - humioscheduledsearches/status
  verbs:
  - get
