# permissions for end users to view humioingesttokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humioingesttoken-viewer-role
rules:
- apiGroups:
  - core.humio.com
  resources:
  - humioingesttokens
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.humio.com
  resources:
  - humioingesttokens/status
  verbs:
  - get
