apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: humioparsers.core.humio.com
spec:
  group: core.humio.com
  names:
    kind: HumioParser
    listKind: HumioParserList
    plural: humioparsers
    singular: humioparser
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: HumioParser is the Schema for the humioparsers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: HumioParserSpec defines the desired state of HumioParser
          properties:
            name:
              type: string
            parser_script:
              type: string
            repository:
              type: string
            tag_fields:
              items:
                type: string
              type: array
            test_data:
              items:
                type: string
              type: array
          type: object
        status:
          description: HumioParserStatus defines the observed state of HumioParser
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
