apiVersion: core.humio.com/v1alpha1
kind: HumioExternalCluster
metadata:
  name: example-humioexternalcluster
  labels:
    app: 'humioexternalcluster'
    app.kubernetes.io/name: 'humioexternalcluster'
    app.kubernetes.io/instance: 'example-humioexternalcluster'
    app.kubernetes.io/managed-by: 'manual'
spec:
  url: "https://example-humiocluster.default:8080/"
  apiTokenSecretName: "example-humiocluster-admin-token"
  caSecretName: "example-humiocluster"
