apiVersion: core.humio.com/v1alpha1
kind: HumioIngestToken
metadata:
  name: example-humioingesttoken-managed
spec:
  managedClusterName: example-humiocluster
  name: example-token
  repositoryName: humio
---
apiVersion: core.humio.com/v1alpha1
kind: HumioIngestToken
metadata:
  name: example-humioingesttoken-external
spec:
  externalClusterName: example-humioexternalcluster
  name: example-token-external
  repositoryName: humio
