apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: humioexternalclusters.core.humio.com
spec:
  group: core.humio.com
  names:
    kind: HumioExternalCluster
    listKind: HumioExternalClusterList
    plural: humioexternalclusters
    singular: humioexternalcluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: HumioExternalCluster is the Schema for the humioexternalclusters
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: HumioExternalClusterSpec defines the desired state of HumioExternalCluster
          properties:
            url:
              type: string
          type: object
        status:
          description: HumioExternalClusterStatus defines the observed state of HumioExternalCluster
          properties:
            version:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
