apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: humiorepositories.core.humio.com
spec:
  group: core.humio.com
  names:
    kind: HumioRepository
    listKind: HumioRepositoryList
    plural: humiorepositories
    singular: humiorepository
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: HumioRepository is the Schema for the humiorepositories API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: HumioRepositorySpec defines the desired state of HumioRepository
          properties:
            description:
              type: string
            name:
              type: string
            retention:
              description: 'HumioRetention defines the retention for the repository
                TODO: this is not implemented in the humio api yet'
              properties:
                ingest_size_in_gb:
                  format: int64
                  type: integer
                storage_size_in_gb:
                  format: int64
                  type: integer
                time_in_days:
                  format: int64
                  type: integer
              type: object
          type: object
        status:
          description: HumioRepositoryStatus defines the observed state of HumioRepository
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
