apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: humio-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: HumioAction is the Schema for the humioactions API
      displayName: Humio Action
      kind: HumioAction
      name: humioactions.core.humio.com
      version: v1alpha1
    - description: HumioAlert is the Schema for the humioalerts API
      displayName: Humio Alert
      kind: HumioAlert
      name: humioalerts.core.humio.com
      version: v1alpha1
    - description: HumioCluster is the Schema for the humioclusters API
      displayName: Humio Cluster
      kind: HumioCluster
      name: humioclusters.core.humio.com
      version: v1alpha1
    - description: HumioExternalCluster is the Schema for the humioexternalclusters
        API
      displayName: Humio External Cluster
      kind: HumioExternalCluster
      name: humioexternalclusters.core.humio.com
      version: v1alpha1
    - description: HumioIngestToken is the Schema for the humioingesttokens API
      displayName: Humio Ingest Token
      kind: HumioIngestToken
      name: humioingesttokens.core.humio.com
      version: v1alpha1
    - description: HumioParser is the Schema for the humioparsers API
      displayName: Humio Parser
      kind: HumioParser
      name: humioparsers.core.humio.com
      version: v1alpha1
    - description: HumioRepository is the Schema for the humiorepositories API
      displayName: Humio Repository
      kind: HumioRepository
      name: humiorepositories.core.humio.com
      version: v1alpha1
    - description: HumioView is the Schema for the humioviews API
      displayName: Humio View
      kind: HumioView
      name: humioviews.core.humio.com
      version: v1alpha1
  description: Operator for managing Humio Clusters
  displayName: Humio Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - humio
  links:
  - name: Humio Operator
    url: https://humio-operator.domain
  maturity: alpha
  provider:
    name: Humio
  version: 0.0.0
