apiVersion: core.humio.com/v1alpha1
kind: HumioIngestToken
metadata:
  labels:
    app.kubernetes.io/name: humio-operator
    app.kubernetes.io/managed-by: kustomize
  name: humioingesttoken-sample
spec:
  managedClusterName: humiocluster-sample
  name: example-token
  repositoryName: humio
  tokenSecretName: humio-ingesttoken
