apiVersion: core.humio.com/v1alpha1
kind: HumioPdfRenderService
metadata:
  name: pdf-render-service
  namespace: logging
spec:
  # Required fields
  image: humio/pdf-render-service:0.0.60--build-101--sha-fe87a59c82fd957ec460190a3f726948d586c1ea
  replicas: 2
  
  # Port configuration
  port: 5123

  
  # Service type (matches the Terraform configuration)
  serviceType: ClusterIP
  
  # Environment variables
  env:
    - name: XDG_CONFIG_HOME
      value: /tmp/.chromium-config
    - name: XDG_CACHE_HOME
      value: /tmp/.chromium-cache
    - name: DEBUG
      value: "true"
  
  # Resource requirements
  resources:
    limits:
      cpu: "2"
      memory: "250Mi"
    requests:
      cpu: "1"
      memory: "250Mi"
  
  # Readiness probe configuration
  readinessProbe:
    httpGet:
      path: /ready
      port: 5123
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 60
    failureThreshold: 1
    successThreshold: 1
  
  # Liveness probe configuration
  livenessProbe:
    httpGet:
      path: /health
      port: 5123
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 60
    failureThreshold: 5
    successThreshold: 1
  
  # Node affinity configuration
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: humio_node_type
            operator: In
            values:
            - core
  
  # Add annotations for service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "5123"

