apiVersion: core.humio.com/v1alpha1
kind: HumioViewPermissionRole
metadata:
  labels:
    app.kubernetes.io/name: humio-operator
    app.kubernetes.io/managed-by: kustomize
  name: humioviewpermissionrole-sample
spec:
  managedClusterName: example-humiocluster
  name: example-view-permission-role
  permissions:
    - ReadAccess
  roleAssignments:
    - repoOrViewName: humio
      groupName: example-group