apiVersion: core.humio.com/v1alpha1
kind: HumioPdfRenderService
metadata:
  labels:
    app.kubernetes.io/name: humiopdfrenderservice
    app.kubernetes.io/instance: humiopdfrenderservice-sample
    app.kubernetes.io/part-of: humio-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: humio-operator
  name: humiopdfrenderservice-sample
spec:
  # TODO(user): Add fields here
