apiVersion: core.humio.com/v1alpha1
kind: HumioExternalCluster
metadata:
  labels:
    app.kubernetes.io/name: humio-operator
    app.kubernetes.io/managed-by: kustomize
  name: humioexternalcluster-sample
spec:
  url: "https://humiocluster-sample.default:8080/"
  apiTokenSecretName: "humiocluster-sample-admin-token"
  caSecretName: "humiocluster-sample"
