apiVersion: core.humio.com/v1alpha1
kind: HumioParser
metadata:
  labels:
    app.kubernetes.io/name: humio-operator
    app.kubernetes.io/managed-by: kustomize
  name: humioparser-sample
spec:
  managedClusterName: humiocluster-sample
  name: "example-humioparser"
  parserScript: "kvParse()"
  repositoryName: "humio"
  tagFields:
  - "@somefield"
  testData:
  - "@rawstring data"
