apiVersion: core.humio.com/v1alpha1
kind: HumioAction
metadata:
  labels:
    app.kubernetes.io/name: humio-operator
    app.kubernetes.io/managed-by: kustomize
  name: humioaction-sample
spec:
  managedClusterName: humiocluster-sample
  name: example-email-action
  viewName: humio
  emailProperties:
    recipients:
      - example@example.com
    subjectTemplate: "{alert_name} has alerted"
    bodyTemplate: |-
      {alert_name} has alerted
      click {url} to see the alert
