apiVersion: core.humio.com/v1alpha1
kind: HumioView
metadata:
  name: example-humioview-managed
spec:
  managedClusterName: example-humiocluster
  name: "example-view"
  description: "This is a view of many repositories"
  connections:
    - repositoryName: "example-repository"
      filter: "*"
