apiVersion: core.humio.com/v1alpha1
kind: HumioRepository
metadata:
  labels:
    app.kubernetes.io/name: humio-operator
    app.kubernetes.io/managed-by: kustomize
  name: humiorepository-sample
spec:
  managedClusterName: humiocluster-sample
  name: "example-repository"
  description: "this is an important message"
  allowDataDeletion: false
  retention:
    ingestSizeInGB: 10
    storageSizeInGB: 5
    timeInDays: 30
