apiVersion: core.humio.com/v1alpha1
kind: HumioSystemPermissionRole
metadata:
  labels:
    app.kubernetes.io/name: humio-operator
    app.kubernetes.io/managed-by: kustomize
  name: humiosystempermissionrole-sample
spec:
  managedClusterName: example-humiocluster
  name: example-system-permission-role
  permissions:
    - ReadHealthCheck
  roleAssignmentGroupNames:
    - example-group
