apiVersion: core.humio.com/v1alpha1
kind: HumioPdfRenderService
metadata:
  name: pdf-render-service
  labels:
    attribution.crowdstrike.com/pag: nextgen-siem
    attribution.crowdstrike.com/pg: logscale-integration
    attribution.crowdstrike.com/pillar: platform
    attribution.crowdstrike.com/team: logscale-infrastructure
    attribution.crowdstrike.com/team-id: b169bdac-69a2-499d-a4a3-8fd611904ff5
  annotations:
    iam.amazonaws.com/role: ''
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "5123"
spec:
  enabled: true
  image: humio/pdf-render-service:0.0.59--build-98--sha-b2bfadbc14733ce3ae1153d555148ee4f3a64013 # Replace with your image and tag
  imagePullPolicy: IfNotPresent
  replicas: 2
  port: 5123
  resources:
    limits:
      cpu: 4
      memory: 2Gi
    requests:
      cpu: 4
      memory: 1Gi
  env:
    - name: XDG_CONFIG_HOME
      value: "/tmp/.chromium-config"
    - name: XDG_CACHE_HOME
      value: "/tmp/.chromium-cache"
    - name: EXAMPLE_ENV_VAR  # Example additional variable
      value: "example_value"
  # The controller automatically adds volume mounts for /app/temp and /tmp.
  # You can override these if necessary, but it's generally not required.
  # volumes:
  #   - name: app-temp
  #     emptyDir:
  #       medium: Memory
  #   - name: tmp
  #     emptyDir:
  #       medium: Memory
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true
  imagePullSecrets:
    - name: regcred
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: humio_node_type  # Default key
                operator: In
                values:
                  - traefik  # Default value
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - pdf-render-service
          topologyKey: kubernetes.io/hostname
  ingress:
    enabled: false  # Disabled by default, as it's not in the Terraform config
    hosts:
      - host: pdf-render-service.example.com
        port: 5123
  livenessProbe:
    failureThreshold: 5
    httpGet:
      path: /health
      port: 5123
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 60
  readinessProbe:
    failureThreshold: 1
    httpGet:
      path: /ready
      port: 5123
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 60
