//go:build !ignore_autogenerated

/*
Copyright 2020 Humio https://humio.com

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadersSource) DeepCopyInto(out *HeadersSource) {
	*out = *in
	in.ValueFrom.DeepCopyInto(&out.ValueFrom)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadersSource.
func (in *HeadersSource) DeepCopy() *HeadersSource {
	if in == nil {
		return nil
	}
	out := new(HeadersSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioAction) DeepCopyInto(out *HumioAction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioAction.
func (in *HumioAction) DeepCopy() *HumioAction {
	if in == nil {
		return nil
	}
	out := new(HumioAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioAction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioActionEmailProperties) DeepCopyInto(out *HumioActionEmailProperties) {
	*out = *in
	if in.Recipients != nil {
		in, out := &in.Recipients, &out.Recipients
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioActionEmailProperties.
func (in *HumioActionEmailProperties) DeepCopy() *HumioActionEmailProperties {
	if in == nil {
		return nil
	}
	out := new(HumioActionEmailProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioActionList) DeepCopyInto(out *HumioActionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HumioAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioActionList.
func (in *HumioActionList) DeepCopy() *HumioActionList {
	if in == nil {
		return nil
	}
	out := new(HumioActionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioActionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioActionOpsGenieProperties) DeepCopyInto(out *HumioActionOpsGenieProperties) {
	*out = *in
	in.GenieKeySource.DeepCopyInto(&out.GenieKeySource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioActionOpsGenieProperties.
func (in *HumioActionOpsGenieProperties) DeepCopy() *HumioActionOpsGenieProperties {
	if in == nil {
		return nil
	}
	out := new(HumioActionOpsGenieProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioActionPagerDutyProperties) DeepCopyInto(out *HumioActionPagerDutyProperties) {
	*out = *in
	in.RoutingKeySource.DeepCopyInto(&out.RoutingKeySource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioActionPagerDutyProperties.
func (in *HumioActionPagerDutyProperties) DeepCopy() *HumioActionPagerDutyProperties {
	if in == nil {
		return nil
	}
	out := new(HumioActionPagerDutyProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioActionRepositoryProperties) DeepCopyInto(out *HumioActionRepositoryProperties) {
	*out = *in
	in.IngestTokenSource.DeepCopyInto(&out.IngestTokenSource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioActionRepositoryProperties.
func (in *HumioActionRepositoryProperties) DeepCopy() *HumioActionRepositoryProperties {
	if in == nil {
		return nil
	}
	out := new(HumioActionRepositoryProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioActionSlackPostMessageProperties) DeepCopyInto(out *HumioActionSlackPostMessageProperties) {
	*out = *in
	in.ApiTokenSource.DeepCopyInto(&out.ApiTokenSource)
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioActionSlackPostMessageProperties.
func (in *HumioActionSlackPostMessageProperties) DeepCopy() *HumioActionSlackPostMessageProperties {
	if in == nil {
		return nil
	}
	out := new(HumioActionSlackPostMessageProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioActionSlackProperties) DeepCopyInto(out *HumioActionSlackProperties) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.UrlSource.DeepCopyInto(&out.UrlSource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioActionSlackProperties.
func (in *HumioActionSlackProperties) DeepCopy() *HumioActionSlackProperties {
	if in == nil {
		return nil
	}
	out := new(HumioActionSlackProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioActionSpec) DeepCopyInto(out *HumioActionSpec) {
	*out = *in
	if in.EmailProperties != nil {
		in, out := &in.EmailProperties, &out.EmailProperties
		*out = new(HumioActionEmailProperties)
		(*in).DeepCopyInto(*out)
	}
	if in.HumioRepositoryProperties != nil {
		in, out := &in.HumioRepositoryProperties, &out.HumioRepositoryProperties
		*out = new(HumioActionRepositoryProperties)
		(*in).DeepCopyInto(*out)
	}
	if in.OpsGenieProperties != nil {
		in, out := &in.OpsGenieProperties, &out.OpsGenieProperties
		*out = new(HumioActionOpsGenieProperties)
		(*in).DeepCopyInto(*out)
	}
	if in.PagerDutyProperties != nil {
		in, out := &in.PagerDutyProperties, &out.PagerDutyProperties
		*out = new(HumioActionPagerDutyProperties)
		(*in).DeepCopyInto(*out)
	}
	if in.SlackProperties != nil {
		in, out := &in.SlackProperties, &out.SlackProperties
		*out = new(HumioActionSlackProperties)
		(*in).DeepCopyInto(*out)
	}
	if in.SlackPostMessageProperties != nil {
		in, out := &in.SlackPostMessageProperties, &out.SlackPostMessageProperties
		*out = new(HumioActionSlackPostMessageProperties)
		(*in).DeepCopyInto(*out)
	}
	if in.VictorOpsProperties != nil {
		in, out := &in.VictorOpsProperties, &out.VictorOpsProperties
		*out = new(HumioActionVictorOpsProperties)
		(*in).DeepCopyInto(*out)
	}
	if in.WebhookProperties != nil {
		in, out := &in.WebhookProperties, &out.WebhookProperties
		*out = new(HumioActionWebhookProperties)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioActionSpec.
func (in *HumioActionSpec) DeepCopy() *HumioActionSpec {
	if in == nil {
		return nil
	}
	out := new(HumioActionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioActionStatus) DeepCopyInto(out *HumioActionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioActionStatus.
func (in *HumioActionStatus) DeepCopy() *HumioActionStatus {
	if in == nil {
		return nil
	}
	out := new(HumioActionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioActionVictorOpsProperties) DeepCopyInto(out *HumioActionVictorOpsProperties) {
	*out = *in
	in.NotifyUrlSource.DeepCopyInto(&out.NotifyUrlSource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioActionVictorOpsProperties.
func (in *HumioActionVictorOpsProperties) DeepCopy() *HumioActionVictorOpsProperties {
	if in == nil {
		return nil
	}
	out := new(HumioActionVictorOpsProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioActionWebhookProperties) DeepCopyInto(out *HumioActionWebhookProperties) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SecretHeaders != nil {
		in, out := &in.SecretHeaders, &out.SecretHeaders
		*out = make([]HeadersSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.UrlSource.DeepCopyInto(&out.UrlSource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioActionWebhookProperties.
func (in *HumioActionWebhookProperties) DeepCopy() *HumioActionWebhookProperties {
	if in == nil {
		return nil
	}
	out := new(HumioActionWebhookProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioAggregateAlert) DeepCopyInto(out *HumioAggregateAlert) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioAggregateAlert.
func (in *HumioAggregateAlert) DeepCopy() *HumioAggregateAlert {
	if in == nil {
		return nil
	}
	out := new(HumioAggregateAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioAggregateAlert) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioAggregateAlertList) DeepCopyInto(out *HumioAggregateAlertList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HumioAggregateAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioAggregateAlertList.
func (in *HumioAggregateAlertList) DeepCopy() *HumioAggregateAlertList {
	if in == nil {
		return nil
	}
	out := new(HumioAggregateAlertList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioAggregateAlertList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioAggregateAlertSpec) DeepCopyInto(out *HumioAggregateAlertSpec) {
	*out = *in
	if in.ThrottleField != nil {
		in, out := &in.ThrottleField, &out.ThrottleField
		*out = new(string)
		**out = **in
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioAggregateAlertSpec.
func (in *HumioAggregateAlertSpec) DeepCopy() *HumioAggregateAlertSpec {
	if in == nil {
		return nil
	}
	out := new(HumioAggregateAlertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioAggregateAlertStatus) DeepCopyInto(out *HumioAggregateAlertStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioAggregateAlertStatus.
func (in *HumioAggregateAlertStatus) DeepCopy() *HumioAggregateAlertStatus {
	if in == nil {
		return nil
	}
	out := new(HumioAggregateAlertStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioAlert) DeepCopyInto(out *HumioAlert) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioAlert.
func (in *HumioAlert) DeepCopy() *HumioAlert {
	if in == nil {
		return nil
	}
	out := new(HumioAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioAlert) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioAlertList) DeepCopyInto(out *HumioAlertList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HumioAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioAlertList.
func (in *HumioAlertList) DeepCopy() *HumioAlertList {
	if in == nil {
		return nil
	}
	out := new(HumioAlertList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioAlertList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioAlertSpec) DeepCopyInto(out *HumioAlertSpec) {
	*out = *in
	in.Query.DeepCopyInto(&out.Query)
	if in.ThrottleField != nil {
		in, out := &in.ThrottleField, &out.ThrottleField
		*out = new(string)
		**out = **in
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioAlertSpec.
func (in *HumioAlertSpec) DeepCopy() *HumioAlertSpec {
	if in == nil {
		return nil
	}
	out := new(HumioAlertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioAlertStatus) DeepCopyInto(out *HumioAlertStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioAlertStatus.
func (in *HumioAlertStatus) DeepCopy() *HumioAlertStatus {
	if in == nil {
		return nil
	}
	out := new(HumioAlertStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioBootstrapToken) DeepCopyInto(out *HumioBootstrapToken) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioBootstrapToken.
func (in *HumioBootstrapToken) DeepCopy() *HumioBootstrapToken {
	if in == nil {
		return nil
	}
	out := new(HumioBootstrapToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioBootstrapToken) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioBootstrapTokenList) DeepCopyInto(out *HumioBootstrapTokenList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HumioBootstrapToken, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioBootstrapTokenList.
func (in *HumioBootstrapTokenList) DeepCopy() *HumioBootstrapTokenList {
	if in == nil {
		return nil
	}
	out := new(HumioBootstrapTokenList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioBootstrapTokenList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioBootstrapTokenSpec) DeepCopyInto(out *HumioBootstrapTokenSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	in.TokenSecret.DeepCopyInto(&out.TokenSecret)
	in.HashedTokenSecret.DeepCopyInto(&out.HashedTokenSecret)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioBootstrapTokenSpec.
func (in *HumioBootstrapTokenSpec) DeepCopy() *HumioBootstrapTokenSpec {
	if in == nil {
		return nil
	}
	out := new(HumioBootstrapTokenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioBootstrapTokenStatus) DeepCopyInto(out *HumioBootstrapTokenStatus) {
	*out = *in
	in.TokenSecretKeyRef.DeepCopyInto(&out.TokenSecretKeyRef)
	in.HashedTokenSecretKeyRef.DeepCopyInto(&out.HashedTokenSecretKeyRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioBootstrapTokenStatus.
func (in *HumioBootstrapTokenStatus) DeepCopy() *HumioBootstrapTokenStatus {
	if in == nil {
		return nil
	}
	out := new(HumioBootstrapTokenStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioCluster) DeepCopyInto(out *HumioCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioCluster.
func (in *HumioCluster) DeepCopy() *HumioCluster {
	if in == nil {
		return nil
	}
	out := new(HumioCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioClusterIngressSpec) DeepCopyInto(out *HumioClusterIngressSpec) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(bool)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioClusterIngressSpec.
func (in *HumioClusterIngressSpec) DeepCopy() *HumioClusterIngressSpec {
	if in == nil {
		return nil
	}
	out := new(HumioClusterIngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioClusterLicenseSpec) DeepCopyInto(out *HumioClusterLicenseSpec) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioClusterLicenseSpec.
func (in *HumioClusterLicenseSpec) DeepCopy() *HumioClusterLicenseSpec {
	if in == nil {
		return nil
	}
	out := new(HumioClusterLicenseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioClusterList) DeepCopyInto(out *HumioClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HumioCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioClusterList.
func (in *HumioClusterList) DeepCopy() *HumioClusterList {
	if in == nil {
		return nil
	}
	out := new(HumioClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioClusterSpec) DeepCopyInto(out *HumioClusterSpec) {
	*out = *in
	out.OperatorFeatureFlags = in.OperatorFeatureFlags
	in.License.DeepCopyInto(&out.License)
	in.HostnameSource.DeepCopyInto(&out.HostnameSource)
	in.ESHostnameSource.DeepCopyInto(&out.ESHostnameSource)
	in.Ingress.DeepCopyInto(&out.Ingress)
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(HumioClusterTLSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HumioHeadlessServiceAnnotations != nil {
		in, out := &in.HumioHeadlessServiceAnnotations, &out.HumioHeadlessServiceAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HumioHeadlessServiceLabels != nil {
		in, out := &in.HumioHeadlessServiceLabels, &out.HumioHeadlessServiceLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.HumioNodeSpec.DeepCopyInto(&out.HumioNodeSpec)
	if in.CommonEnvironmentVariables != nil {
		in, out := &in.CommonEnvironmentVariables, &out.CommonEnvironmentVariables
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodePools != nil {
		in, out := &in.NodePools, &out.NodePools
		*out = make([]HumioNodePoolSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioClusterSpec.
func (in *HumioClusterSpec) DeepCopy() *HumioClusterSpec {
	if in == nil {
		return nil
	}
	out := new(HumioClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioClusterStatus) DeepCopyInto(out *HumioClusterStatus) {
	*out = *in
	if in.PodStatus != nil {
		in, out := &in.PodStatus, &out.PodStatus
		*out = make(HumioPodStatusList, len(*in))
		copy(*out, *in)
	}
	out.LicenseStatus = in.LicenseStatus
	if in.NodePoolStatus != nil {
		in, out := &in.NodePoolStatus, &out.NodePoolStatus
		*out = make(HumioNodePoolStatusList, len(*in))
		copy(*out, *in)
	}
	if in.EvictedNodeIds != nil {
		in, out := &in.EvictedNodeIds, &out.EvictedNodeIds
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioClusterStatus.
func (in *HumioClusterStatus) DeepCopy() *HumioClusterStatus {
	if in == nil {
		return nil
	}
	out := new(HumioClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioClusterTLSSpec) DeepCopyInto(out *HumioClusterTLSSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExtraHostnames != nil {
		in, out := &in.ExtraHostnames, &out.ExtraHostnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioClusterTLSSpec.
func (in *HumioClusterTLSSpec) DeepCopy() *HumioClusterTLSSpec {
	if in == nil {
		return nil
	}
	out := new(HumioClusterTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioESHostnameSource) DeepCopyInto(out *HumioESHostnameSource) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioESHostnameSource.
func (in *HumioESHostnameSource) DeepCopy() *HumioESHostnameSource {
	if in == nil {
		return nil
	}
	out := new(HumioESHostnameSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioExternalCluster) DeepCopyInto(out *HumioExternalCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioExternalCluster.
func (in *HumioExternalCluster) DeepCopy() *HumioExternalCluster {
	if in == nil {
		return nil
	}
	out := new(HumioExternalCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioExternalCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioExternalClusterList) DeepCopyInto(out *HumioExternalClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HumioExternalCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioExternalClusterList.
func (in *HumioExternalClusterList) DeepCopy() *HumioExternalClusterList {
	if in == nil {
		return nil
	}
	out := new(HumioExternalClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioExternalClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioExternalClusterSpec) DeepCopyInto(out *HumioExternalClusterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioExternalClusterSpec.
func (in *HumioExternalClusterSpec) DeepCopy() *HumioExternalClusterSpec {
	if in == nil {
		return nil
	}
	out := new(HumioExternalClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioExternalClusterStatus) DeepCopyInto(out *HumioExternalClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioExternalClusterStatus.
func (in *HumioExternalClusterStatus) DeepCopy() *HumioExternalClusterStatus {
	if in == nil {
		return nil
	}
	out := new(HumioExternalClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioFeatureFlag) DeepCopyInto(out *HumioFeatureFlag) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioFeatureFlag.
func (in *HumioFeatureFlag) DeepCopy() *HumioFeatureFlag {
	if in == nil {
		return nil
	}
	out := new(HumioFeatureFlag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioFeatureFlag) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioFeatureFlagList) DeepCopyInto(out *HumioFeatureFlagList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HumioFeatureFlag, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioFeatureFlagList.
func (in *HumioFeatureFlagList) DeepCopy() *HumioFeatureFlagList {
	if in == nil {
		return nil
	}
	out := new(HumioFeatureFlagList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioFeatureFlagList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioFeatureFlagSpec) DeepCopyInto(out *HumioFeatureFlagSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioFeatureFlagSpec.
func (in *HumioFeatureFlagSpec) DeepCopy() *HumioFeatureFlagSpec {
	if in == nil {
		return nil
	}
	out := new(HumioFeatureFlagSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioFeatureFlagStatus) DeepCopyInto(out *HumioFeatureFlagStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioFeatureFlagStatus.
func (in *HumioFeatureFlagStatus) DeepCopy() *HumioFeatureFlagStatus {
	if in == nil {
		return nil
	}
	out := new(HumioFeatureFlagStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioFilterAlert) DeepCopyInto(out *HumioFilterAlert) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioFilterAlert.
func (in *HumioFilterAlert) DeepCopy() *HumioFilterAlert {
	if in == nil {
		return nil
	}
	out := new(HumioFilterAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioFilterAlert) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioFilterAlertList) DeepCopyInto(out *HumioFilterAlertList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HumioFilterAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioFilterAlertList.
func (in *HumioFilterAlertList) DeepCopy() *HumioFilterAlertList {
	if in == nil {
		return nil
	}
	out := new(HumioFilterAlertList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioFilterAlertList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioFilterAlertSpec) DeepCopyInto(out *HumioFilterAlertSpec) {
	*out = *in
	if in.ThrottleField != nil {
		in, out := &in.ThrottleField, &out.ThrottleField
		*out = new(string)
		**out = **in
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioFilterAlertSpec.
func (in *HumioFilterAlertSpec) DeepCopy() *HumioFilterAlertSpec {
	if in == nil {
		return nil
	}
	out := new(HumioFilterAlertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioFilterAlertStatus) DeepCopyInto(out *HumioFilterAlertStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioFilterAlertStatus.
func (in *HumioFilterAlertStatus) DeepCopy() *HumioFilterAlertStatus {
	if in == nil {
		return nil
	}
	out := new(HumioFilterAlertStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioHashedTokenSecretSpec) DeepCopyInto(out *HumioHashedTokenSecretSpec) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioHashedTokenSecretSpec.
func (in *HumioHashedTokenSecretSpec) DeepCopy() *HumioHashedTokenSecretSpec {
	if in == nil {
		return nil
	}
	out := new(HumioHashedTokenSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioHashedTokenSecretStatus) DeepCopyInto(out *HumioHashedTokenSecretStatus) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioHashedTokenSecretStatus.
func (in *HumioHashedTokenSecretStatus) DeepCopy() *HumioHashedTokenSecretStatus {
	if in == nil {
		return nil
	}
	out := new(HumioHashedTokenSecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioHostnameSource) DeepCopyInto(out *HumioHostnameSource) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioHostnameSource.
func (in *HumioHostnameSource) DeepCopy() *HumioHostnameSource {
	if in == nil {
		return nil
	}
	out := new(HumioHostnameSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioImageSource) DeepCopyInto(out *HumioImageSource) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(v1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioImageSource.
func (in *HumioImageSource) DeepCopy() *HumioImageSource {
	if in == nil {
		return nil
	}
	out := new(HumioImageSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioIngestToken) DeepCopyInto(out *HumioIngestToken) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioIngestToken.
func (in *HumioIngestToken) DeepCopy() *HumioIngestToken {
	if in == nil {
		return nil
	}
	out := new(HumioIngestToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioIngestToken) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioIngestTokenList) DeepCopyInto(out *HumioIngestTokenList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HumioIngestToken, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioIngestTokenList.
func (in *HumioIngestTokenList) DeepCopy() *HumioIngestTokenList {
	if in == nil {
		return nil
	}
	out := new(HumioIngestTokenList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioIngestTokenList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioIngestTokenSpec) DeepCopyInto(out *HumioIngestTokenSpec) {
	*out = *in
	if in.ParserName != nil {
		in, out := &in.ParserName, &out.ParserName
		*out = new(string)
		**out = **in
	}
	if in.TokenSecretLabels != nil {
		in, out := &in.TokenSecretLabels, &out.TokenSecretLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TokenSecretAnnotations != nil {
		in, out := &in.TokenSecretAnnotations, &out.TokenSecretAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioIngestTokenSpec.
func (in *HumioIngestTokenSpec) DeepCopy() *HumioIngestTokenSpec {
	if in == nil {
		return nil
	}
	out := new(HumioIngestTokenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioIngestTokenStatus) DeepCopyInto(out *HumioIngestTokenStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioIngestTokenStatus.
func (in *HumioIngestTokenStatus) DeepCopy() *HumioIngestTokenStatus {
	if in == nil {
		return nil
	}
	out := new(HumioIngestTokenStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioLicenseStatus) DeepCopyInto(out *HumioLicenseStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioLicenseStatus.
func (in *HumioLicenseStatus) DeepCopy() *HumioLicenseStatus {
	if in == nil {
		return nil
	}
	out := new(HumioLicenseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioNodePoolFeatures) DeepCopyInto(out *HumioNodePoolFeatures) {
	*out = *in
	if in.AllowedAPIRequestTypes != nil {
		in, out := &in.AllowedAPIRequestTypes, &out.AllowedAPIRequestTypes
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioNodePoolFeatures.
func (in *HumioNodePoolFeatures) DeepCopy() *HumioNodePoolFeatures {
	if in == nil {
		return nil
	}
	out := new(HumioNodePoolFeatures)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioNodePoolSpec) DeepCopyInto(out *HumioNodePoolSpec) {
	*out = *in
	in.HumioNodeSpec.DeepCopyInto(&out.HumioNodeSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioNodePoolSpec.
func (in *HumioNodePoolSpec) DeepCopy() *HumioNodePoolSpec {
	if in == nil {
		return nil
	}
	out := new(HumioNodePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioNodePoolStatus) DeepCopyInto(out *HumioNodePoolStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioNodePoolStatus.
func (in *HumioNodePoolStatus) DeepCopy() *HumioNodePoolStatus {
	if in == nil {
		return nil
	}
	out := new(HumioNodePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in HumioNodePoolStatusList) DeepCopyInto(out *HumioNodePoolStatusList) {
	{
		in := &in
		*out = make(HumioNodePoolStatusList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioNodePoolStatusList.
func (in HumioNodePoolStatusList) DeepCopy() HumioNodePoolStatusList {
	if in == nil {
		return nil
	}
	out := new(HumioNodePoolStatusList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioNodeSpec) DeepCopyInto(out *HumioNodeSpec) {
	*out = *in
	if in.ImageSource != nil {
		in, out := &in.ImageSource, &out.ImageSource
		*out = new(HumioImageSource)
		(*in).DeepCopyInto(*out)
	}
	in.DataVolumePersistentVolumeClaimSpecTemplate.DeepCopyInto(&out.DataVolumePersistentVolumeClaimSpecTemplate)
	out.DataVolumePersistentVolumeClaimPolicy = in.DataVolumePersistentVolumeClaimPolicy
	in.DataVolumeSource.DeepCopyInto(&out.DataVolumeSource)
	if in.EnvironmentVariablesSource != nil {
		in, out := &in.EnvironmentVariablesSource, &out.EnvironmentVariablesSource
		*out = make([]v1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ShareProcessNamespace != nil {
		in, out := &in.ShareProcessNamespace, &out.ShareProcessNamespace
		*out = new(bool)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.ContainerSecurityContext != nil {
		in, out := &in.ContainerSecurityContext, &out.ContainerSecurityContext
		*out = new(v1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerReadinessProbe != nil {
		in, out := &in.ContainerReadinessProbe, &out.ContainerReadinessProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerLivenessProbe != nil {
		in, out := &in.ContainerLivenessProbe, &out.ContainerLivenessProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerStartupProbe != nil {
		in, out := &in.ContainerStartupProbe, &out.ContainerStartupProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	in.Affinity.DeepCopyInto(&out.Affinity)
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SidecarContainers != nil {
		in, out := &in.SidecarContainers, &out.SidecarContainers
		*out = make([]v1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraHumioVolumeMounts != nil {
		in, out := &in.ExtraHumioVolumeMounts, &out.ExtraHumioVolumeMounts
		*out = make([]v1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraVolumes != nil {
		in, out := &in.ExtraVolumes, &out.ExtraVolumes
		*out = make([]v1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HumioServiceAccountAnnotations != nil {
		in, out := &in.HumioServiceAccountAnnotations, &out.HumioServiceAccountAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HumioServiceLabels != nil {
		in, out := &in.HumioServiceLabels, &out.HumioServiceLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EnvironmentVariables != nil {
		in, out := &in.EnvironmentVariables, &out.EnvironmentVariables
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HumioServiceAnnotations != nil {
		in, out := &in.HumioServiceAnnotations, &out.HumioServiceAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.UpdateStrategy != nil {
		in, out := &in.UpdateStrategy, &out.UpdateStrategy
		*out = new(HumioUpdateStrategy)
		(*in).DeepCopyInto(*out)
	}
	in.NodePoolFeatures.DeepCopyInto(&out.NodePoolFeatures)
	if in.PodDisruptionBudget != nil {
		in, out := &in.PodDisruptionBudget, &out.PodDisruptionBudget
		*out = new(HumioPodDisruptionBudgetSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioNodeSpec.
func (in *HumioNodeSpec) DeepCopy() *HumioNodeSpec {
	if in == nil {
		return nil
	}
	out := new(HumioNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioOperatorFeatureFlags) DeepCopyInto(out *HumioOperatorFeatureFlags) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioOperatorFeatureFlags.
func (in *HumioOperatorFeatureFlags) DeepCopy() *HumioOperatorFeatureFlags {
	if in == nil {
		return nil
	}
	out := new(HumioOperatorFeatureFlags)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioParser) DeepCopyInto(out *HumioParser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioParser.
func (in *HumioParser) DeepCopy() *HumioParser {
	if in == nil {
		return nil
	}
	out := new(HumioParser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioParser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioParserList) DeepCopyInto(out *HumioParserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HumioParser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioParserList.
func (in *HumioParserList) DeepCopy() *HumioParserList {
	if in == nil {
		return nil
	}
	out := new(HumioParserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioParserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioParserSpec) DeepCopyInto(out *HumioParserSpec) {
	*out = *in
	if in.TagFields != nil {
		in, out := &in.TagFields, &out.TagFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TestData != nil {
		in, out := &in.TestData, &out.TestData
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioParserSpec.
func (in *HumioParserSpec) DeepCopy() *HumioParserSpec {
	if in == nil {
		return nil
	}
	out := new(HumioParserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioParserStatus) DeepCopyInto(out *HumioParserStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioParserStatus.
func (in *HumioParserStatus) DeepCopy() *HumioParserStatus {
	if in == nil {
		return nil
	}
	out := new(HumioParserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioPersistentVolumeClaimPolicy) DeepCopyInto(out *HumioPersistentVolumeClaimPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioPersistentVolumeClaimPolicy.
func (in *HumioPersistentVolumeClaimPolicy) DeepCopy() *HumioPersistentVolumeClaimPolicy {
	if in == nil {
		return nil
	}
	out := new(HumioPersistentVolumeClaimPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioPodDisruptionBudgetSpec) DeepCopyInto(out *HumioPodDisruptionBudgetSpec) {
	*out = *in
	if in.MinAvailable != nil {
		in, out := &in.MinAvailable, &out.MinAvailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.UnhealthyPodEvictionPolicy != nil {
		in, out := &in.UnhealthyPodEvictionPolicy, &out.UnhealthyPodEvictionPolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioPodDisruptionBudgetSpec.
func (in *HumioPodDisruptionBudgetSpec) DeepCopy() *HumioPodDisruptionBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(HumioPodDisruptionBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioPodStatus) DeepCopyInto(out *HumioPodStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioPodStatus.
func (in *HumioPodStatus) DeepCopy() *HumioPodStatus {
	if in == nil {
		return nil
	}
	out := new(HumioPodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in HumioPodStatusList) DeepCopyInto(out *HumioPodStatusList) {
	{
		in := &in
		*out = make(HumioPodStatusList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioPodStatusList.
func (in HumioPodStatusList) DeepCopy() HumioPodStatusList {
	if in == nil {
		return nil
	}
	out := new(HumioPodStatusList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioQuery) DeepCopyInto(out *HumioQuery) {
	*out = *in
	if in.IsLive != nil {
		in, out := &in.IsLive, &out.IsLive
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioQuery.
func (in *HumioQuery) DeepCopy() *HumioQuery {
	if in == nil {
		return nil
	}
	out := new(HumioQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioRepository) DeepCopyInto(out *HumioRepository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioRepository.
func (in *HumioRepository) DeepCopy() *HumioRepository {
	if in == nil {
		return nil
	}
	out := new(HumioRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioRepository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioRepositoryList) DeepCopyInto(out *HumioRepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HumioRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioRepositoryList.
func (in *HumioRepositoryList) DeepCopy() *HumioRepositoryList {
	if in == nil {
		return nil
	}
	out := new(HumioRepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioRepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioRepositorySpec) DeepCopyInto(out *HumioRepositorySpec) {
	*out = *in
	in.Retention.DeepCopyInto(&out.Retention)
	if in.AutomaticSearch != nil {
		in, out := &in.AutomaticSearch, &out.AutomaticSearch
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioRepositorySpec.
func (in *HumioRepositorySpec) DeepCopy() *HumioRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(HumioRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioRepositoryStatus) DeepCopyInto(out *HumioRepositoryStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioRepositoryStatus.
func (in *HumioRepositoryStatus) DeepCopy() *HumioRepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(HumioRepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioRetention) DeepCopyInto(out *HumioRetention) {
	*out = *in
	if in.IngestSizeInGB != nil {
		in, out := &in.IngestSizeInGB, &out.IngestSizeInGB
		*out = new(int32)
		**out = **in
	}
	if in.StorageSizeInGB != nil {
		in, out := &in.StorageSizeInGB, &out.StorageSizeInGB
		*out = new(int32)
		**out = **in
	}
	if in.TimeInDays != nil {
		in, out := &in.TimeInDays, &out.TimeInDays
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioRetention.
func (in *HumioRetention) DeepCopy() *HumioRetention {
	if in == nil {
		return nil
	}
	out := new(HumioRetention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioScheduledSearch) DeepCopyInto(out *HumioScheduledSearch) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioScheduledSearch.
func (in *HumioScheduledSearch) DeepCopy() *HumioScheduledSearch {
	if in == nil {
		return nil
	}
	out := new(HumioScheduledSearch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioScheduledSearch) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioScheduledSearchList) DeepCopyInto(out *HumioScheduledSearchList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HumioScheduledSearch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioScheduledSearchList.
func (in *HumioScheduledSearchList) DeepCopy() *HumioScheduledSearchList {
	if in == nil {
		return nil
	}
	out := new(HumioScheduledSearchList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioScheduledSearchList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioScheduledSearchSpec) DeepCopyInto(out *HumioScheduledSearchSpec) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioScheduledSearchSpec.
func (in *HumioScheduledSearchSpec) DeepCopy() *HumioScheduledSearchSpec {
	if in == nil {
		return nil
	}
	out := new(HumioScheduledSearchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioScheduledSearchStatus) DeepCopyInto(out *HumioScheduledSearchStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioScheduledSearchStatus.
func (in *HumioScheduledSearchStatus) DeepCopy() *HumioScheduledSearchStatus {
	if in == nil {
		return nil
	}
	out := new(HumioScheduledSearchStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioTokenSecretSpec) DeepCopyInto(out *HumioTokenSecretSpec) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioTokenSecretSpec.
func (in *HumioTokenSecretSpec) DeepCopy() *HumioTokenSecretSpec {
	if in == nil {
		return nil
	}
	out := new(HumioTokenSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioTokenSecretStatus) DeepCopyInto(out *HumioTokenSecretStatus) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioTokenSecretStatus.
func (in *HumioTokenSecretStatus) DeepCopy() *HumioTokenSecretStatus {
	if in == nil {
		return nil
	}
	out := new(HumioTokenSecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioUpdateStrategy) DeepCopyInto(out *HumioUpdateStrategy) {
	*out = *in
	if in.EnableZoneAwareness != nil {
		in, out := &in.EnableZoneAwareness, &out.EnableZoneAwareness
		*out = new(bool)
		**out = **in
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioUpdateStrategy.
func (in *HumioUpdateStrategy) DeepCopy() *HumioUpdateStrategy {
	if in == nil {
		return nil
	}
	out := new(HumioUpdateStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioView) DeepCopyInto(out *HumioView) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioView.
func (in *HumioView) DeepCopy() *HumioView {
	if in == nil {
		return nil
	}
	out := new(HumioView)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioView) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioViewConnection) DeepCopyInto(out *HumioViewConnection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioViewConnection.
func (in *HumioViewConnection) DeepCopy() *HumioViewConnection {
	if in == nil {
		return nil
	}
	out := new(HumioViewConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioViewList) DeepCopyInto(out *HumioViewList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HumioView, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioViewList.
func (in *HumioViewList) DeepCopy() *HumioViewList {
	if in == nil {
		return nil
	}
	out := new(HumioViewList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioViewList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioViewSpec) DeepCopyInto(out *HumioViewSpec) {
	*out = *in
	if in.Connections != nil {
		in, out := &in.Connections, &out.Connections
		*out = make([]HumioViewConnection, len(*in))
		copy(*out, *in)
	}
	if in.AutomaticSearch != nil {
		in, out := &in.AutomaticSearch, &out.AutomaticSearch
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioViewSpec.
func (in *HumioViewSpec) DeepCopy() *HumioViewSpec {
	if in == nil {
		return nil
	}
	out := new(HumioViewSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioViewStatus) DeepCopyInto(out *HumioViewStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioViewStatus.
func (in *HumioViewStatus) DeepCopy() *HumioViewStatus {
	if in == nil {
		return nil
	}
	out := new(HumioViewStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VarSource) DeepCopyInto(out *VarSource) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VarSource.
func (in *VarSource) DeepCopy() *VarSource {
	if in == nil {
		return nil
	}
	out := new(VarSource)
	in.DeepCopyInto(out)
	return out
}
