apiVersion: core.humio.com/v1alpha1
kind: HumioCluster
metadata:
  name: example-humiocluster
spec:
  license:
    secretKeyRef:
      name: example-humiocluster-license
      key: data
  image: "humio/humio-core:1.34.0"
  nodeCount: 1
  tls:
    enabled: false
  targetReplicationFactor: 1
  storagePartitionsCount: 24
  digestPartitionsCount: 24
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 2Gi
  dataVolumePersistentVolumeClaimSpecTemplate:
    storageClassName: standard
    accessModes: [ReadWriteOnce]
    resources:
      requests:
        storage: 10Gi
  environmentVariables:
    - name: "HUMIO_MEMORY_OPTS"
      value: "-Xss2m -Xms1g -Xmx2g -XX:MaxDirectMemorySize=1g"
    - name: "HUMIO_GC_OPTS"
      value: "-XX:+UseParallelGC"
    - name: "HUMIO_JVM_LOG_OPTS"
      value: "-Xlog:gc+jni=debug:stdout -Xlog:gc*:stdout:time,tags"
    - name: "HUMIO_OPTS"
      value: "-Dlog4j2.formatMsgNoLookups=true -Dakka.log-config-on-start=on"
    - name: "ZOOKEEPER_URL"
      value: "humio-cp-zookeeper-0.humio-cp-zookeeper-headless.default:2181"
    - name: "KAFKA_SERVERS"
      value: "humio-cp-kafka-0.humio-cp-kafka-headless.default:9092"
    - name: AUTHENTICATION_METHOD
      value: "single-user"
    - name: SINGLE_USER_PASSWORD
      value: "password"
