apiVersion: core.humio.com/v1alpha1
kind: HumioAction
metadata:
  name: example-email-action-managed
spec:
  managedClusterName: example-humiocluster
  name: example-email-action
  viewName: humio
  emailProperties:
    recipients:
      - example@example.com
    subjectTemplate: "{alert_name} has alerted"
    bodyTemplate: |-
      {alert_name} has alerted
      click {url} to see the alert
---
apiVersion: core.humio.com/v1alpha1
kind: HumioAction
metadata:
  name: example-email-action-external
spec:
  externalClusterName: example-humioexternalcluster
  name: example-email-action
  viewName: humio
  emailProperties:
    recipients:
      - example@example.com
    subjectTemplate: "{alert_name} has alerted"
    bodyTemplate: |-
      {alert_name} has alerted
      click {url} to see the alert
