apiVersion: core.humio.com/v1alpha1
kind: HumioParser
metadata:
  name: example-humioparser-managed
spec:
  managedClusterName: example-humiocluster
  name: "example-humioparser"
  parserScript: "kvParse()"
  repositoryName: "humio"
  tagFields:
  - "@somefield"
  testData:
  - "@rawstring data"
---
apiVersion: core.humio.com/v1alpha1
kind: HumioParser
metadata:
  name: example-humioparser-external
spec:
  externalClusterName: example-humioexternalcluster
  name: "example-humioparser"
  parserScript: "kvParse()"
  repositoryName: "humio"
  tagFields:
  - "@somefield"
  testData:
  - "@rawstring data"
