apiVersion: core.humio.com/v1alpha1
kind: HumioAction
metadata:
  name: humio-victor-ops-action-managed
spec:
  managedClusterName: example-humiocluster
  name: example-victor-ops-action
  viewName: humio
  victorOpsProperties:
    messageType: critical
    notifyUrl: "https://alert.victorops.com/integrations/0000/alert/0000/routing_key"
---
apiVersion: core.humio.com/v1alpha1
kind: HumioAction
metadata:
  name: humio-victor-ops-action-external
spec:
  externalClusterName: example-humioexternalcluster
  name: example-victor-ops-action
  viewName: humio
  victorOpsProperties:
    messageType: critical
    notifyUrl: "https://alert.victorops.com/integrations/0000/alert/0000/routing_key"
