apiVersion: core.humio.com/v1alpha1
kind: HumioCluster
metadata:
  name: example-humiocluster
spec:
  #disableInitContainer: true
  nodePools:
    - name: ingest-only
      spec:
        #disableInitContainer: true
        image: "humio/humio-core:1.82.1"
        nodeCount: 1
        dataVolumePersistentVolumeClaimSpecTemplate:
          storageClassName: standard
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 10Gi
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 2Gi
        environmentVariables:
          - name: "HUMIO_MEMORY_OPTS"
            value: "-Xss2m -Xms1g -Xmx2g -XX:MaxDirectMemorySize=1g"
          - name: "ZOOKEEPER_URL"
            value: "humio-cp-zookeeper-0.humio-cp-zookeeper-headless.default:2181"
          - name: "KAFKA_SERVERS"
            value: "humio-cp-kafka-0.humio-cp-kafka-headless.default:9092"
              #          - name: "STATIC_USERS"
              #            value: "user:user"
          - name: "AUTHENTICATION_METHOD"
            value: "static"
  license:
    secretKeyRef:
      name: example-humiocluster-license
      key: data
  image: "humio/humio-core:1.82.1"
  nodeCount: 0
  tls:
    enabled: false
  targetReplicationFactor: 1
  storagePartitionsCount: 24
  digestPartitionsCount: 24
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 2Gi
  dataVolumePersistentVolumeClaimSpecTemplate:
    storageClassName: standard
    accessModes: [ReadWriteOnce]
    resources:
      requests:
        storage: 10Gi
  environmentVariables:
    - name: "HUMIO_MEMORY_OPTS"
      value: "-Xss2m -Xms1g -Xmx2g -XX:MaxDirectMemorySize=1g"
    - name: "ZOOKEEPER_URL"
      value: "humio-cp-zookeeper-0.humio-cp-zookeeper-headless.default:2181"
    - name: "KAFKA_SERVERS"
      value: "humio-cp-kafka-0.humio-cp-kafka-headless.default:9092"
