apiVersion: core.humio.com/v1alpha1
kind: HumioFilterAlert
metadata:
  name: example-alert-filter-managed
spec:
  managedClusterName: example-humiocluster
  name: example-filter-alert
  viewName: humio
  queryString: "#repo = humio | error = true"
  enabled: true
  description: Error counts
  actions:
    - example-email-action
---
apiVersion: core.humio.com/v1alpha1
kind: HumioFilterAlert
metadata:
  name: example-alert-filter-external
spec:
  externalClusterName: example-humioexternalcluster
  name: example-filter-alert
  viewName: humio
  queryString: "#repo = humio | error = true"
  enabled: true
  description: Error counts
  actions:
    - example-email-action
