apiVersion: core.humio.com/v1alpha1
kind: HumioAction
metadata:
  name: humio-humio-repository-action-managed
spec:
  managedClusterName: example-humiocluster
  name: example-humio-repository-action
  viewName: humio
  humioRepositoryProperties:
    ingestToken: some-humio-ingest-token
---
apiVersion: core.humio.com/v1alpha1
kind: HumioAction
metadata:
  name: humio-humio-repository-action-external
spec:
  externalClusterName: example-humioexternalcluster
  name: example-humio-repository-action
  viewName: humio
  humioRepositoryProperties:
    ingestToken: some-humio-ingest-token
