apiVersion: core.humio.com/v1alpha1
kind: HumioAction
metadata:
  name: humio-web-hook-action-managed
spec:
  managedClusterName: example-humiocluster
  name: example-web-hook-action
  viewName: humio
  webhookProperties:
    url: "https://example.com/some/api"
    headers:
      some: header
      some-other: header
    method: POST
    bodyTemplate: |-
      {alert_name} has alerted
      click {url} to see the alert
---
apiVersion: core.humio.com/v1alpha1
kind: HumioAction
metadata:
  name: humio-web-hook-action-external
spec:
  externalClusterName: example-humioexternalcluster
  name: example-web-hook-action
  viewName: humio
  webhookProperties:
    url: "https://example.com/some/api"
    headers:
      some: header
      some-other: header
    method: POST
    bodyTemplate: |-
      {alert_name} has alerted
      click {url} to see the alert
---
apiVersion: core.humio.com/v1alpha1
kind: HumioAction
metadata:
  name: humio-web-hook-action-mixed-headers-external
spec:
  externalClusterName: example-humioexternalcluster
  name: example-web-hook-action-using-secrets
  viewName: humio
  webhookProperties:
    urlSource:
      secretKeyRef:
        name: example-humiocluster-webhook-action-url-secret
        key: data
    headers:
      some: header
      some-other: header
    secretHeaders:
      - name: this
        valueFrom:
          secretKeyRef:
            name: example-humiocluster-webhook-action-headers-secret
            key: somesecretheader
    method: POST
    bodyTemplate: |-
      {alert_name} has alerted
      click {url} to see the alert
---
apiVersion: core.humio.com/v1alpha1
kind: HumioAction
metadata:
  name: humio-web-hook-action-all-secret-external
spec:
  externalClusterName: example-humioexternalcluster
  name: example-web-hook-action-using-secret-url-and-headers
  viewName: humio
  webhookProperties:
    urlSource:
      secretKeyRef:
        name: example-humiocluster-webhook-action-url-secret
        key: data
    secretHeaders:
      - name: this
        valueFrom:
          secretKeyRef:
            name: example-humiocluster-webhook-action-headers-secret
            key: somesecretheader
    method: POST
    bodyTemplate: |-
      {alert_name} has alerted
      click {url} to see the alert
