apiVersion: core.humio.com/v1alpha1
kind: HumioAction
metadata:
  name: humio-pagerduty-action-managed
spec:
  managedClusterName: example-humiocluster
  name: example-pagerduty-action
  viewName: humio
  pagerDutyProperties:
    routingKey: some-routing-key
    severity: critical
---
apiVersion: core.humio.com/v1alpha1
kind: HumioAction
metadata:
  name: humio-pagerduty-action-external
spec:
  externalClusterName: example-humioexternalcluster
  name: example-pagerduty-action
  viewName: humio
  pagerDutyProperties:
    routingKey: some-routing-key
    severity: critical
