apiVersion: core.humio.com/v1alpha1
kind: HumioScheduledSearch
metadata:
  name: example-scheduled-search-managed
spec:
  managedClusterName: example-humiocluster
  name: example-scheduled-search
  viewName: humio
  queryString: "#repo = humio | error = true | count()"
  queryStart: "1h"
  queryEnd: "now"
  schedule: "1h"
  timeZone: "UTC"
  backfillLimit: 3
  enabled: true
  description: Error counts
  actions:
    - example-email-action
---
apiVersion: core.humio.com/v1alpha1
kind: HumioScheduledSearch
metadata:
  name: example-scheduled-search-external
spec:
  externalClusterName: example-humioexternalcluster
  name: example-scheduled-search
  viewName: humio
  queryString: "#repo = humio | error = true | count()"
  queryStart: "1h"
  queryEnd: "now"
  schedule: "1h"
  timeZone: "UTC"
  backfillLimit: 3
  enabled: true
  description: Error counts
  actions:
    - example-email-action
