apiVersion: core.humio.com/v1alpha1
kind: HumioRepository
metadata:
  name: example-humiorepository-managed
spec:
  managedClusterName: example-humiocluster
  name: "example-repository"
  description: "this is an important message"
  # Data deletion must be explicitly enabled before the operator will apply/lower retention settings that may cause data to be deleted.
  allowDataDeletion: false
  retention:
    # If retention options are left out they will not be set.
    ingestSizeInGB: 10
    storageSizeInGB: 5
    timeInDays: 30
---
apiVersion: core.humio.com/v1alpha1
kind: HumioRepository
metadata:
  name: example-humiorepository-external
spec:
  # The operator needs the HumioExternalCluster to use an API token that has access to create repositories.
  externalClusterName: example-humioexternalcluster
  name: "example-repository"
  description: "this is an important message"
  # Data deletion must be explicitly enabled before the operator will apply/lower retention settings that may cause data to be deleted.
  allowDataDeletion: false
  retention:
    # If retention options are left out they will not be set.
    ingestSizeInGB: 10
    storageSizeInGB: 5
    timeInDays: 30
