apiVersion: core.humio.com/v1alpha1
kind: HumioAlert
metadata:
  name: example-alert-managed
spec:
  managedClusterName: example-humiocluster
  name: example-alert
  viewName: humio
  query:
    queryString: "#repo = humio | error = true | count() | _count > 0"
    start: 24h
    end: now
    isLive: true
  throttleTimeMillis: 60000
  silenced: false
  description: Error counts
  actions:
      - example-email-action
---
apiVersion: core.humio.com/v1alpha1
kind: HumioAlert
metadata:
  name: example-alert-external
spec:
  externalClusterName: example-humioexternalcluster
  name: example-alert
  viewName: humio
  query:
    queryString: "#repo = humio | error = true | count() | _count > 0"
    start: 24h
    end: now
    isLive: true
  throttleTimeMillis: 60000
  silenced: false
  description: Error counts
  actions:
    - example-email-action
