apiVersion: core.humio.com/v1alpha1
kind: HumioView
metadata:
  name: example-humioview-managed
spec:
  managedClusterName: example-humiocluster
  Name: "example-view"
  description: "this is an important message"
  connections:
    - repositoryName: "example-repository"
      filter: "*"
