apiVersion: core.humio.com/v1alpha1
kind: HumioAggregateAlert
metadata:
  name: example-aggregate-alert-managed
spec:
  managedClusterName: example-humiocluster
  name: example-aggregate-alert
  queryString: "#repo = humio | error = true | count()"
  queryTimestampType: "EventTimestamp"
  viewName: "humio"
  throttleTimeSeconds: 60
  triggerMode: "CompleteMode"
  searchIntervalSeconds: 60
  throttleField: "@timestamp"
  description: "This is an example of an aggregate alert"
  enabled: true
  actions:
    - example-email-action

---

apiVersion: core.humio.com/v1alpha1
kind: HumioAggregateAlert
metadata:
  name: example-aggregate-alert-external
spec:
  externalClusterName: example-humioexternalcluster
  name: example-aggregate-alert-external
  queryString: "#repo = humio | error = true | count()"
  queryTimestampType: "EventTimestamp"
  viewName: "humio"
  throttleTimeSeconds: 60
  triggerMode: "CompleteMode"
  searchIntervalSeconds: 60
  throttleField: "@timestamp"
  description: "This is an example of an aggregate alert"
  enabled: true
  actions:
    - example-email-action
