apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Basic Install
    categories: "Monitoring,Logging & Tracing"
    certified: "false"
    description: Operator for running the Humio log management, streaming and observability service
    createdAt: "2020-04-23 08:00:00"
    support: Humio, Inc.
    repository: github.com/humio/humio-operator
    containerImage: humio/humio-operator:v0.0.1
    alm-examples: |-
      [
        {
          "apiVersion": "core.humio.com/v1alpha1",
          "kind": "HumioCluster",
          "metadata": {
            "name": "example-humiocluster"
          },
          "spec": {
            "environmentVariables": [
              {
                "name": "ZOOKEEPER_URL",
                "value": "humio-cp-zookeeper-0.humio-cp-zookeeper-headless:2181"
              },
              {
                "name": "KAFKA_SERVERS",
                "value": "humio-cp-kafka-0.humio-cp-kafka-headless:9092"
              }
            ],
            "image": "humio/humio-core:1.10.1"
          }
        },
        {
          "apiVersion": "core.humio.com/v1alpha1",
          "kind": "HumioExternalCluster",
          "metadata": {
            "name": "example-humioexternalcluster"
          },
          "spec": {
            "url": "http://example-humiocluster.default:8080/"
          }
        },
        {
          "apiVersion": "core.humio.com/v1alpha1",
          "kind": "HumioIngestToken",
          "metadata": {
            "name": "example-humioingesttoken-external"
          },
          "spec": {
            "externalClusterName": "example-humioexternalcluster",
            "name": "example-token-external",
            "repositoryName": "humio"
          }
        },
        {
          "apiVersion": "core.humio.com/v1alpha1",
          "kind": "HumioIngestToken",
          "metadata": {
            "name": "example-humioingesttoken-managed"
          },
          "spec": {
            "managedClusterName": "example-humiocluster",
            "name": "example-token",
            "repositoryName": "humio"
          }
        },
        {
          "apiVersion": "core.humio.com/v1alpha1",
          "kind": "HumioParser",
          "metadata": {
            "name": "example-humioparser"
          },
          "spec": {
            "name": null,
            "parser_script": null,
            "respository": null,
            "tag_fields": [
              "@somefield"
            ],
            "test_data": [
              "@rawstring data"
            ]
          }
        },
        {
          "apiVersion": "core.humio.com/v1alpha1",
          "kind": "HumioRepository",
          "metadata": {
            "name": "example-humiorepository"
          },
          "spec": {
            "description": null,
            "name": null,
            "retention": {
              "ingest_size_in_gb": 10,
              "storage_size_in_gb": 5,
              "time_in_days": 30
            }
          }
        }
      ]
  name: humio-operator.v0.0.1
  namespace: placeholder
spec:
  provider:
    name: Humio Inc.
  links:
    - name: Humio
      url:  https://humio.com
    - name: Humio Operator GitHub
      url: https://github.com/humio/humio-operator
  maintainers:
    - name: Mike Rostermund
      email: mike@humio.com
    - name: Jestin Woods
      email: jestin@humio.com
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: HumioCluster is the Schema for the humioclusters API
      displayName: Humio Cluster
      kind: HumioCluster
      name: humioclusters.core.humio.com
      version: v1alpha1
    - description: HumioExternalCluster is the Schema for the humioexternalclusters
        API
      displayName: Humio External Cluster
      kind: HumioExternalCluster
      name: humioexternalclusters.core.humio.com
      version: v1alpha1
    - description: HumioIngestToken is the Schema for the humioingesttokens API
      displayName: Humio Ingest Token
      kind: HumioIngestToken
      name: humioingesttokens.core.humio.com
      version: v1alpha1
    - description: HumioParser is the Schema for the humioparsers API
      displayName: Humio Parser
      kind: HumioParser
      name: humioparsers.core.humio.com
      version: v1alpha1
    - description: HumioRepository is the Schema for the humiorepositories API
      displayName: Humio Repository
      kind: HumioRepository
      name: humiorepositories.core.humio.com
      version: v1alpha1
  description: Placeholder description
  displayName: Humio Operator
  install:
    spec:
      deployments:
      - name: humio-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: humio-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: humio-operator
            spec:
              containers:
              - command:
                - humio-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: humio-operator
                image: humio/humio-operator:dev
                name: humio-operator
                resources: {}
              serviceAccountName: humio-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          - serviceaccounts
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - humio-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - core.humio.com
          resources:
          - '*'
          - humioparsers
          - humioingesttokens
          - humiorepositories
          - humioexternalclusters
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - humio.com
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - roles
          - rolebindings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: humio-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  replaces: humio-operator.v0.0.0
  version: 0.0.1
  icon:
    - base64data: iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAABXtSURBVHgB7V0NdBzVdb53ZvUv2zLxn2TZGhEHuy6xcQ1NaAhaGdeBJhyg1ElO29SmSQ9wchIgh7Skpzmy0yQQSPlpOHBOe4gFAZrGodg5Cf9GK/P/U5DToJBgpJEsaWXLllc/lrTa3bm9b2ZWWu2+mZ390XrB+c4ZaXbmzZs3975373333fceQpGiRvPXVAOcx6cbYwAa8gFAfGANAtUQJ0lMz/dDBBji/zqZ56CrfPCtQ+MAHSE9EIIiBEKRQBC8CuBKPm1i4vktYucVHeJAwAAztH1QD+hQBDitDLBr+Q4m+JUE5IcCQjCC/7WebmacFgbUa34/E72l0ER3Bu7j8jwY1AP7oMAoGAPitd0AuhFMeV6U0Lll7OrXAw9CgVAQBqzU/Ex0aklWnOlAJkEgwMXUDVOhoo6I+iQZI8lKVTC4ApVFRKQprKTBVOAklLhmnWeEgjFiXhkgRA3X+D3gscaTRWQWB7hvCuhQviwXwZxywI1sPbGSpyvRewucd0bMCwNWaH5RC+8Cy6pJhxAz6W5EX2uw+/keKABE+fjDb8iAGa0G4O75UNZ5ZwCLm538YXelEzd8P0Cg7BrU29rhNGKF1tykgCH0UrrKMi+tIW8MsO34XWzZ3OCWrlgInwyr1UILl3CnWzr+vrsnQdmdL/GYFwbYIqcNXJpzsRI+GZZ4oj1odgYdwUYBNudDJOXMABY5wtpocxE5oSjgNcdOg42dC5gRO5kRLS46Qo8AXjWkBzogB6iQA4S85yb5JJ+WOyTZN8E15USOhTwdGA/pHdU1jftZ7tsmbQpqmHjXVdU06OOhnkOQJbJmgLDtmfj3O9wOxYBuGdQP3jQV0qfgAwpmQmgspO9nRoywfvgkSCoaM+hKcZ/TvgpZICsRZBP/Ltk9Mr2R+ZGPxQRbN7Q5iST+5pvYlXE3ZIiMW4Atdu6XFwI6JgEvPK4HBuFDBtEaLJFkKucVyff5+qXZiKOMWoBQuEz8t2X32FXQOsW1oFj97vmCxuZ2GOBubg07ZPdZMW/KRDF7ZoCbqSmIP6i3XwNnEGo1f6sDE7hnj5u8imBPDBCdrEqr5mvJ985E4sfhwgSdrb9NXqSBAh4gerggIb6Q+ULswBmKMgDhwpCJG60CjBbwgLQtwFa6e5KvF9ra2bx5c8nAwIJFqmoshhJaDKRWEkI1l0FRiEa5PFwXosPGlG/4oouWnty7d28MCgBLJ9DbKJUOtJNNcVffkSsDXOS+o5yrbdyyzUdGJShqv2rEjuh64CiY/MoGLUpdY+ASheAiFnV/Lj6SM6p1Tk+cDI+xWOghwtf5x5NnVQ0d6OzsnIYscc45/iVjYWU1orGKf1YM6IGfJqcRdFKZCRJvQFp94MqAOs2/R+ac4k7WjUf1g/d4eYYLFeGXBPl0gH8cBwUHkWCcr48g0igQjRuoTKh8L8IF9nFNZsKtQKK/5NJdDhKTLyMgjKEB+xRF+blB1MsdJ5YctDhGeJZKRhWpsICZtZDLuEi0KDSMs0i8E7GOH2ZmU9nst2AH2/qbZK9hfXAjSvpGnNe+oN5+lXPxHOAkehitAy5K14lpHwa4MUCgTmt6HCRubdtxF5A9ozi/jFpSr5lewN3wB0hRyk5HEZ+UfF2RV2T7ngTWoIrM6sFdHzYXQz7B+k7IfJl00GrNcfFUSBngUPsDg/kfG53mjPv4eItrzqssQ1/ja718TED+IZyCR+Lv4v9vsp4ZMMuQR4jQFjIDCeZCuLZFfyr5ui/5gi37teTrJOdsxiCCKCJ0Mu8fMRSjjU6VdR49+syp+P01ay4rm5ycWke+2GZE/Csuy6Vc/KychuJdCtJbiOrDfH7QCFe9Fwz+coa5S5f6q5UqONdnRVBcw4T7U8gDmFa7MTXmqaYCYAfLpznGS8qHsSLphlTx46p45z7vooSJuIOIP2RZeSs3Vy9uaqW2YcsViLH7IHNrSMSHtgR1/70Au410iQUzSquMq5l4nB6qZWnSKeFE1GpNbZJRNZ3p2Jh4YY4IWqX5hQbXkjPLj+KldyMxZSMXoMUj8c1XB3uef3zKN7WWP+ZJ8I5XMTK5hs2/f/dCfIGhocB4P3eaCNVz+efLkCNITjON+wz+xAtzGMBdxx2pGcG+PCjeXgrHPjPUFzgMWWD48GujiyqXiRCS/0mfmp6hMF7e3//6CcgCIjSGn7+C83kLcoAwO510QeLvGQaI3hyYgUtzwQPpGQ8yJOEEEV0aDL7UCzmgs3PvtBFe8CU+/bVjIoLDpJT+QzAYOA45QDxfrpRusQLFsoesFQixlKiMZxigSqIARAFyjmIgagn2HPwt5AFCgRoKfIU/YkRyO8y169pg13M5MTqOrq7nRthK+lc+nYQsIVqBrF9QkSBpEq0giVsVc41k6JhA5RG3BIvP3rqoPBr9OCr0MSTl2Fhs6pXRvleGndIPdrW/wYbCY3z694nX2Vp6aqDnYJvbu1asuGypWhX+OEWjmoJK14Sv4q3hw0+OOqXn/H7M79rOp5dCluBWwBKEdiVdFZLGtIbMFiDEjyxUnJJMJi9gg3GWqUQ/cvOJ1zY0/3WlEfktE/8F/vljQuOX1b6ynrrV/tsAtjsPl5L6AJhDEbMv4sI+BA5Ov9razZXcEbpFKZ94h2KxA1zIB9hT2VYenehha+Xr/JijmasAztAAsxhD50Km9J0SxZDJAGfxk7nyZXl/vn0aDsciTzulY3P1i+xh/M9U7yZVA9LNddqx7zs9G5vy8bgrJog17Jsgw6H2Eyrl1dexeLqVfyxNulnDjsE7LSY4PB1R32CCWS2SaKVwi0MGsGiIevJ1HmO5Qvw3GcBEaEp9NHPxI2xp/rcOrEyPn+jbFpSlW7L2Uwv4vrC3K6UZIdcJgq+uqJ9rssVhdtyQEk3Fd0d6XzwpS1vXuOUc9nZ+B5yAZmDCd2rP/tRq2e3+/gPDZPXORdolR44u+iPIEMzAFFrGJY5iJaDzUhNkzoDyBTbxrUzfd7LBKyMln2ACfgTcgFClqHC1020WOr+Jn/NL3nPMhuAvOHUVuL4KF0KsZJvTq/jojP9Q1egayBBs3u+XXPaLP4oY0SFJ5JeIz4cMwcMhS2bOAR0VacwATx9BSI7pWDbPKE8esHEMg+GatgE8gHXXSuc8Et6FygLIEOUOw5ZCDyhRCfEpy2mdhoFj8XM24aod05FxDDyBHNPxYM4MIZjIixxzADwJnl4FpxzfReSbTQZhyBC6SctUPcCMOU+IoI2yZyALlKnYl/CzzsmSKSFD1IhxSAMExdH9wIRtmEmH6Fh7FQV+Bem9qxTB6eecbnLrOHs2pZFtPyOQki/Tnltvqu+HZWJWwbTd3c+Lwg2JczbsVi5aHVwoS9fb+2IXv/xR18wInpsarXhCfnM7j2BSoudy8/Ll26Ryvr+r7QB/0TPgBoN+MaS/LBW5LKK5opKp24R3dXK09B3IDroseykDYnKZlRb1jVsuANs+ZwIvrFRKHN27GC3/FnPpXvOzEiA+kv+9EInh9cPD8k7SqlUnNGbQpoRnGtXyqY1O75rywdc4jcyPNM3Xfz6NFdeDQx8iAriWzLFhsyVMlS+KXghZgOnRk3qVuEMoievnFpCx/K/X/JeybH+eT5fHs2Hr6jqn9H19Tw+XInyTQL2MKSg6Vs8wMfaywP3qgL5sq5vjzlBjX4YEl7Ho/LEYcrSYhg8H+oypsr/jlF9kq+gnpsMO4WEVcEewx/+F4z1PB+VPmh20a2G2A1bN+mBvbYP/byBDoEMLQO4QdScvC8AuWS2TCXMNDdsaI0q4g+tQksihCYNg+2DPwScgT1i9+rOLo8qpVzjvtfY7RCgKD7vCMLeaT2TrcZWhrmHrJsCI6G8kh6WHwYhdMtD74kses4qH+HQnXdYVtObUzoGYhwsesX799tIIhv8tlfgCWKkg3mrJ0XygRYniqdvjxGfSP8Pe2p9Yr4KzSlW6Z/369aWQB4jvYuL/AOSTT8pAUe9w0jsylEuccowaRTa1KBMTNBQ+KlwPl7sk2RABuj8fhKlvEKNyZI7MscvDUGL4T5Xq9D/yL1NXsMC4LDSxVHgwsxrCnAXh6MSQ6D1vdUl0YWlp5BLwCF1O0xpPsaFuoJgpe32uadjTOjK+5HbbVZHNW1A40wyku23XgUBLf3/g0Pvvv3wMSRV+d2FqCr1zY73WvMvv9/uyedP27dvVuobm2w2imyENI6OqsRNyRM4MQPfZhDPJSMEbSqrosfr6iz8GGWD58j9btlJrvp+V33dhVvHuiU6YA0Wm5dLf03Ynk96MvWGLpdQA49vvddOeFWs+vTSTdy2t/8yal9849iig8Y0ERjuCv/1PsmV0HDkxwJbtdRk8ss3w4a/rGpr+o75+ywZR2+TJCJet2vJRMRVKrSz5P7b5rxUEsU3U1vHh6ZvFGG7iEwPd7NEk5Q77J7I4+lslquhsZNxWX+9f09LSIv1WIRrrGpvX1mrNd5b6wq8yRz9vKnUP4HItfutweCHkAFypNZ1M1gMTgIu96AHhR2L53k0ZLsJhgXikCX/Dtegd/hD25ShTCjtajJixRChZNivP53xnXQwIY2Aodwz0tH0P5owFzClP+TTBVzgtM4JmlSfBOMumN4mU9zjPQXZjxDh/Zr6xnHXJOub3+fxMJWSOKe4nNA55mJIlaDUNlOwWCfnItPnnWkJi1ZGQXGvnEcgjc3ABE+QCS9QS+5LIlrqY2isSYy4GisAtxygHEW1R/1H/U2TQNzn5rHvZDGNnUYmGH2eyo5mbuapsL5iSK9yQMENTCC2WfAEPGC+LxJiBBYnDZyotUNTYz1Y0NF3mlIKJv4Zi9PQc4hcJfPIJLjqboaleOtXjem3V4RKWQJT1oHWmECKJa8yjybE1AvWNn97ALUjM2D8bCoep2GiFpzBKlItp0QJSu8gy/5AMZoAVWs63AoKbMj2+crX/c/ELJvFB+RUXvB4KCprYsGHSEwNiUq8z6j57mcfkjDXwjnf58BSul0fUsE30cO2qLZ+PktHFIlPE5ReY+Kap9ftAIBD1mFy23IEuBmRkblg/eAT3R7Oaop8rWM4vUnyxn5X44NkCi53ZMgC84TUtygOeOxS34TLwAB7wEIFbnuIv8w3BhAxba37fb9BzXtK5DfsqbsNl4AHhsuku/vd7ONNA1HeKIm96Seo27Bs3TQPJCdCOW0mH4797aYx7nR6CZj9kQHzZLYIvESShJdqSxw5LgfbUBKmBui54Cs4wsGPwMa9pSUJLw1q512JAiSRwCMS8psYtDeABaqT8Ha4ReRsIKXYIdwYPmrR5SWtFnUvNerPSmwwQekAay07e3K1ieJFNwfvgDAH3Q/YPDr7gqf+jmstjzoU930638ppJKIuEM5cZ9laoiE8Ex6Y6pQhO4rz7leYF3MFC2bDsNEaVH4JHkHTOBbbGz2cY4JNE8TJqZN1+Gfr7D5wgxORQdOJr32KOf0OMYMEHCAbCbVzu62wX+Az42k/7PI4711u00yS3ZnTuDAMcxZBkyqoTSmLqfXNrO7Wp0fBDA3o7MxcfgA8ImA7PrmvAW4P60mfZRZ64NsQ0GcYPvOZjyMXPnClfytyb8ik1XltBb++BLs7kR3ZmMTTU7/f1vTJplmUa/5nbw/9C8aNn4mTsC5aLYW8sElV2QXyWDMHDg70vdHrJxGnKl5EgfgTmMMCeWKYnP5RJK4hOlYkawoWkQ/29IirNgph3VYrKVqTcZyDOGwj6J8PRi0dGZkPdjx15vgutdVGPTZ8y/sVrVtYqvMnZg35UD+xPSjcXqjmlZi4yaQUidl9BlQfPzfm2cyDEHMbKRQTF21BsIOrEaOyzJ1MnE/I4ENzDVfd7x4+/EPSSlV37d6a8AnBX8rWUsSCnYUahH4J6ezN4h2CuVPHW1n6uUikde5B70FdDQcaj3MHf1qZEJre7TG1F+/BkSPBYdlvylC9R+4NJk7QFUlqAveCEVBcssyZye4VjYcVsxxLELyEpN3NnYwxOH8JspX17aqTkqjTzioXH3ivxd8rn26XWfgHH2lerNXVLluEK8YB9Y76WphSD6NFo7BwqUR5hc+9cKCSIW7lB15eparuut4XNuTQ5wmmFMafaL+CyXpB0cY6aCpe1b7xCxNKsbGz672kWdYZP+S4L2YwnPeQKRJwGRf2yKEOd1vxkff2FFZAjbMWrJV93qv0CjsFH4yFdX1CjCTfqusTr3CrW5bJWskDEp9Vxt0z0C0Sg1VrONJPYonxhCSL8sV2GNYSlT4yNdB+BLGHvk3OL5FYr1/7dTs+5BiCxLrhJ5kYQZqntZMoKsSh4iSYLsZi4V7gyIFsQiJ31HuKjK13SKBrLIEvYVk9WK4y5MkD02GLydUHFwHib11GzLBEa6Dn4tYGe9iUKKJ9krn/d6uTRL8BaL2Iw8WBXh+ggPcVpuDeON8VIvWSgZ2h5v96+g697nJOWOeJyXxac5mWFsbQ1kTNoXaldvJEzS3bMaRVC4Wj+5nleL9ro09tEQNZrUGQwZzmCGRCgJd8TW50Mmi4Yd3iKgSwBZbe8hwznVTosY38mgLW26LTKhht1sc+Mlzw8McBy1GGzg1t5Z53WlIVllNY7mreNHwwvK54Y6WdtJsJp3ej4isJepYLn6Gh7zQOnnrDJBK86odpXEWQ5LVyyQkm+jtas95A5d8tqaSEkehjyBAKlFcz1HmiA3/eE9S5zWyqzDMJJOD0KngbYxTe6LNotJpBflckaGxm7AcTmNk7rYIqRfvJYgPXr/dUnJ5WPqJFJVpALK6K+8MJBvam3trb9LN/CSOmR320d9LrcmAdgbe3WVbAgOlFlVIydMiLLI6OVJ6urRyPczFbEKuH4UGcgbQuwV5EXHS1pxIiXtaJTCgZZwGmZXht52+KpmJBuqy635ZzdkNUmPqITJjpjKF/IqIav7+T74Vw6a8UE0cli4v8XOKzcmC3xBXLyRLqJIxvztgdjIWCLHPF9jk7IbMROInJ2BYt9ZbgQj6NzRLVe6D168wEWs1eKyuUy+4cNCGzuz3GPtLz44tNt8WS9yNzL/Zpibw1edvvO5+YVeRsMsQZyjBZJjzkZRSmWvG6zXpSbeSbCwx6M8Vfv407IPX0O6+oXChnsby/2Pb4xF3kvw7wMB3rdGtaGaM5ixfF7CtUquLVq02ypcUW5gbzN8NwnPMMfiA2dE+G9NczAZAbbxvvHs1y1SwZhzbDT/zzWQVegadF4m1NgyXpl53xuwTuvDIgjC0bE0WHPXeAeNhxSrT1mdDGFNpk5gshclWuiYG70I44GtP77vRI8AWIz0l3Z2vaZoCAMiCMHRhQElh8KWcnCg4XakrGgDIijTvNfYeuHTKIs5g10Gnf7Pi0MiMMe1vQLz6LHRT/yBisOFvcVsrbLcFoZkIg4MxRzFV9zIVlPc9S8gsweOQTEzBT2gO4vll1fi4YByRBKtRxwo72qr+hpa7bJqNmzzlN2rSNrfMH09dsrAIj/HWI2YrFus/v/Rt3Nzenaii4AAAAASUVORK5CYII=
      mediatype: image/png
