//go:build !ignore_autogenerated

/*
Copyright 2020 Humio https://humio.com

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioScheduledSearch) DeepCopyInto(out *HumioScheduledSearch) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioScheduledSearch.
func (in *HumioScheduledSearch) DeepCopy() *HumioScheduledSearch {
	if in == nil {
		return nil
	}
	out := new(HumioScheduledSearch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioScheduledSearch) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioScheduledSearchList) DeepCopyInto(out *HumioScheduledSearchList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HumioScheduledSearch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioScheduledSearchList.
func (in *HumioScheduledSearchList) DeepCopy() *HumioScheduledSearchList {
	if in == nil {
		return nil
	}
	out := new(HumioScheduledSearchList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumioScheduledSearchList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioScheduledSearchSpec) DeepCopyInto(out *HumioScheduledSearchSpec) {
	*out = *in
	if in.SearchIntervalOffsetSeconds != nil {
		in, out := &in.SearchIntervalOffsetSeconds, &out.SearchIntervalOffsetSeconds
		*out = new(int64)
		**out = **in
	}
	if in.BackfillLimit != nil {
		in, out := &in.BackfillLimit, &out.BackfillLimit
		*out = new(int)
		**out = **in
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioScheduledSearchSpec.
func (in *HumioScheduledSearchSpec) DeepCopy() *HumioScheduledSearchSpec {
	if in == nil {
		return nil
	}
	out := new(HumioScheduledSearchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumioScheduledSearchStatus) DeepCopyInto(out *HumioScheduledSearchStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumioScheduledSearchStatus.
func (in *HumioScheduledSearchStatus) DeepCopy() *HumioScheduledSearchStatus {
	if in == nil {
		return nil
	}
	out := new(HumioScheduledSearchStatus)
	in.DeepCopyInto(out)
	return out
}
