{{- if .Values.operator.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}'
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "humio.labels" . | nindent 4 }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.operator.metrics.listen.port }}
    protocol: TCP
    targetPort: {{ .Values.operator.metrics.listen.port }}
  selector:
    app: '{{ .Chart.Name }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
{{- end }}
