apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}'
  namespace: '{{ .Release.Namespace }}'
  labels:
    app: '{{ .Chart.Name }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: '{{ .Chart.Name }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
