# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/core.humio.com_humioexternalclusters.yaml
- bases/core.humio.com_humioclusters.yaml
- bases/core.humio.com_humioingesttokens.yaml
- bases/core.humio.com_humioparsers.yaml
- bases/core.humio.com_humiorepositories.yaml
- bases/core.humio.com_humioviews.yaml
- bases/core.humio.com_humioactions.yaml
- bases/core.humio.com_humioalerts.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_humioexternalclusters.yaml
#- patches/webhook_in_humioclusters.yaml
#- patches/webhook_in_humioingesttokens.yaml
#- patches/webhook_in_humioparsers.yaml
#- patches/webhook_in_humiorepositories.yaml
#- patches/webhook_in_humioviews.yaml
#- patches/webhook_in_humioactions.yaml
#- patches/webhook_in_humioalerts.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_humioexternalclusters.yaml
#- patches/cainjection_in_humioclusters.yaml
#- patches/cainjection_in_humioingesttokens.yaml
#- patches/cainjection_in_humioparsers.yaml
#- patches/cainjection_in_humiorepositories.yaml
#- patches/cainjection_in_humioviews.yaml
#- patches/cainjection_in_humioactions.yaml
#- patches/cainjection_in_humioalerts.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
