apiVersion: apps/v1
kind: Deployment
metadata:
  name: humio-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: humio-operator
  template:
    metadata:
      labels:
        name: humio-operator
    spec:
      serviceAccountName: humio-operator
      containers:
        - name: humio-operator
          image: humio/humio-operator:master
          command:
          - humio-operator
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "humio-operator"
