---
apiVersion: core.humio.com/v1alpha1
kind: HumioPdfRenderService
metadata:
  name: test-pdf-service
spec:
  image: "humio/pdf-render-service:0.1.2--build-104--sha-9a7598de95bb9775b6f59d874c37a206713bae01"
  replicas: 1
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: "500m" 
      memory: 512Mi