operator:
  image:
    repository: humio/humio-operator
    tag:
    pullPolicy: IfNotPresent
    pullSecrets: []
  metrics:
    enabled: true
    listen:
      port: 8080
    secure: false
  prometheus:
    serviceMonitor:
      enabled: false
  rbac:
    create: true
    allowManageRoles: true
    allowManageClusterRoles: true
  resources:
    limits:
      cpu: 250m
      memory: 200Mi
    requests:
      cpu: 250m
      memory: 200Mi
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
            - arm64
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
certmanager: true
defaultHumioCoreImage: ""
defaultHumioHelperImageManaged: "humio/humio-operator-helper:18b8d8df927ae03ead82162ba8f1171960c1b275"
