on: pull_request
name: e2e
jobs:
  e2e:
    name: ${{ matrix.kind-k8s-version }}
    runs-on: [self-hosted, ops]
    strategy:
      fail-fast: false
      matrix:
        kind-k8s-version:
          - kindest/node:v1.25.16@sha256:6110314339b3b44d10da7d27881849a87e092124afab5956f2e10ecdb463b025 # Not officially supported by kind 0.26.0
          - kindest/node:v1.26.15@sha256:1cc15d7b1edd2126ef051e359bf864f37bbcf1568e61be4d2ed1df7a3e87b354 # Not officially supported by kind 0.26.0
          - kindest/node:v1.27.17@sha256:3fd82731af34efe19cd54ea5c25e882985bafa2c9baefe14f8deab1737d9fabe # Not officially supported by kind 0.26.0
          - kindest/node:v1.28.13@sha256:45d319897776e11167e4698f6b14938eb4d52eb381d9e3d7a9086c16c69a8110 # Not officially supported by kind 0.26.0
          - kindest/node:v1.29.12@sha256:62c0672ba99a4afd7396512848d6fc382906b8f33349ae68fb1dbfe549f70dec
          - kindest/node:v1.30.8@sha256:17cd608b3971338d9180b00776cb766c50d0a0b6b904ab4ff52fd3fc5c6369bf
          - kindest/node:v1.31.4@sha256:2cb39f7295fe7eafee0842b1052a599a4fb0f8bcf3f83d96c7f4864c357c6c30
          - kindest/node:v1.32.0@sha256:c48c62eac5da28cdadcf560d1d8616cfa6783b58f0d94cf63ad1bf49600cb027
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23.6'
    - name: cleanup kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.26.0/kind-linux-amd64
        chmod +x ./kind
        ./kind delete cluster || true
        make clean
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Get temp bin dir
      id: bin_dir
      run: echo "BIN_DIR=$(mktemp -d --tmpdir=${{ github.workspace }})" >> $GITHUB_OUTPUT
    - name: run e2e tests
      env:
        BIN_DIR: ${{ steps.bin_dir.outputs.BIN_DIR }}
        HUMIO_E2E_LICENSE: ${{ secrets.HUMIO_E2E_LICENSE }}
        E2E_KIND_K8S_VERSION: ${{ matrix.kind-k8s-version }}
        E2E_LOGS_HUMIO_HOSTNAME: ${{ secrets.E2E_LOGS_HUMIO_HOSTNAME }}
        E2E_LOGS_HUMIO_INGEST_TOKEN: ${{ secrets.E2E_LOGS_HUMIO_INGEST_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        GINKGO_NODES: "6"
      run: |
        hack/run-e2e-using-kind.sh
    - name: cleanup kind and docker files
      if: always()
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.26.0/kind-linux-amd64
        chmod +x ./kind
        ./kind delete cluster || true
        make clean
