on: pull_request
name: e2e
jobs:
  e2e:
    name: ${{ matrix.kind-k8s-version }}
    runs-on: [self-hosted, ops]
    strategy:
      fail-fast: false
      matrix:
        kind-k8s-version:
          - kindest/node:v1.19.11@sha256:07db187ae84b4b7de440a73886f008cf903fcf5764ba8106a9fd5243d6f32729
          - kindest/node:v1.20.7@sha256:cbeaf907fc78ac97ce7b625e4bf0de16e3ea725daf6b04f930bd14c67c671ff9
          - kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
          - kindest/node:v1.22.0@sha256:b8bda84bb3a190e6e028b1760d277454a72267a5454b57db34437c34a588d047
    steps:
    - uses: actions/checkout@v2
    - name: cleanup kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
        chmod +x ./kind
        ./kind delete cluster || true
    - uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.11.1"
        image: ${{ matrix.kind-k8s-version }}
    - name: Get temp bin dir
      id: bin_dir
      run: echo ::set-output name=BIN_DIR::$(mktemp -d --tmpdir=${{ github.workspace }})
    - name: run e2e tests
      env:
        BIN_DIR: ${{ steps.bin_dir.outputs.BIN_DIR }}
        HUMIO_E2E_LICENSE: ${{ secrets.HUMIO_E2E_LICENSE }}
        E2E_KIND_K8S_VERSION: ${{ matrix.kind-k8s-version }}
        E2E_LOGS_HUMIO_HOSTNAME: ${{ secrets.E2E_LOGS_HUMIO_HOSTNAME }}
        E2E_LOGS_HUMIO_INGEST_TOKEN: ${{ secrets.E2E_LOGS_HUMIO_INGEST_TOKEN }}
        E2E_RUN_ID: ${{ github.run_id }}
        GINKGO_NODES: "6"
      run: |
        make run-e2e-tests-ci-kind
    - name: cleanup kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
        chmod +x ./kind
        ./kind delete cluster || true
