on: pull_request
name: e2e
jobs:
  e2e:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: engineerd/setup-kind@v0.3.0
      with:
          version: "v0.7.0"
    - name: Get temp bin dir
      id: bin_dir
      run: echo ::set-output name=BIN_DIR::$(mktemp -d --tmpdir=${{ github.workspace }})
    - name: run e2e tests
      env:
        BIN_DIR: ${{ steps.bin_dir.outputs.BIN_DIR }}
      run: |
        make run-e2e-tests
