on: pull_request
name: e2e
jobs:
  e2e:
    name: ${{ matrix.kind-k8s-version }}
    runs-on: [self-hosted, ops]
    strategy:
      fail-fast: false
      matrix:
        kind-k8s-version:
          - kindest/node:v1.19.16@sha256:81f552397c1e6c1f293f967ecb1344d8857613fb978f963c30e907c32f598467
          - kindest/node:v1.20.15@sha256:393bb9096c6c4d723bb17bceb0896407d7db581532d11ea2839c80b28e5d8deb
          - kindest/node:v1.21.10@sha256:84709f09756ba4f863769bdcabe5edafc2ada72d3c8c44d6515fc581b66b029c
          - kindest/node:v1.22.7@sha256:1dfd72d193bf7da64765fd2f2898f78663b9ba366c2aa74be1fd7498a1873166
          - kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.7'
    - name: cleanup kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
        chmod +x ./kind
        ./kind delete cluster || true
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.12.0"
        image: ${{ matrix.kind-k8s-version }}
    - name: Get temp bin dir
      id: bin_dir
      run: echo ::set-output name=BIN_DIR::$(mktemp -d --tmpdir=${{ github.workspace }})
    - name: run e2e tests
      env:
        BIN_DIR: ${{ steps.bin_dir.outputs.BIN_DIR }}
        HUMIO_E2E_LICENSE: ${{ secrets.HUMIO_E2E_LICENSE }}
        E2E_KIND_K8S_VERSION: ${{ matrix.kind-k8s-version }}
        E2E_LOGS_HUMIO_HOSTNAME: ${{ secrets.E2E_LOGS_HUMIO_HOSTNAME }}
        E2E_LOGS_HUMIO_INGEST_TOKEN: ${{ secrets.E2E_LOGS_HUMIO_INGEST_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        GINKGO_NODES: "6"
      run: |
        make run-e2e-tests-ci-kind
    - name: cleanup kind
      if: always()
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
        chmod +x ./kind
        ./kind delete cluster || true
