on: pull_request
name: e2e
jobs:
  e2e:
    name: ${{ matrix.kind-k8s-version }}
    runs-on: [self-hosted, ops]
    strategy:
      fail-fast: false
      matrix:
        kind-k8s-version:
          - kindest/node:v1.21.14@sha256:75047f07ef306beff928fdc1f171a8b81fae1628f7515bdabc4fc9c31b698d6b
          - kindest/node:v1.22.17@sha256:ed0f6a1cd1dcc0ff8b66257b3867e4c9e6a54adeb9ca31005f62638ad555315c
          - kindest/node:v1.23.17@sha256:f935044f60483d33648d8c13decd79557cf3e916363a3c9ba7e82332cb249cba
          - kindest/node:v1.24.12@sha256:0bdca26bd7fe65c823640b14253ea7bac4baad9336b332c94850f84d8102f873
          - kindest/node:v1.25.8@sha256:b5ce984f5651f44457edf263c1fe93459df8d5d63db7f108ccf5ea4b8d4d9820
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.19.9'
    - name: cleanup kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.16.0/kind-linux-amd64
        chmod +x ./kind
        ./kind delete cluster || true
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.16.0"
        image: ${{ matrix.kind-k8s-version }}
    - name: Get temp bin dir
      id: bin_dir
      run: echo "BIN_DIR=$(mktemp -d --tmpdir=${{ github.workspace }})" >> $GITHUB_OUTPUT
    - name: run e2e tests
      env:
        BIN_DIR: ${{ steps.bin_dir.outputs.BIN_DIR }}
        HUMIO_E2E_LICENSE: ${{ secrets.HUMIO_E2E_LICENSE }}
        E2E_KIND_K8S_VERSION: ${{ matrix.kind-k8s-version }}
        E2E_LOGS_HUMIO_HOSTNAME: ${{ secrets.E2E_LOGS_HUMIO_HOSTNAME }}
        E2E_LOGS_HUMIO_INGEST_TOKEN: ${{ secrets.E2E_LOGS_HUMIO_INGEST_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        GINKGO_NODES: "6"
      run: |
        which go
        go version
        make run-e2e-tests-ci-kind
    - name: cleanup kind
      if: always()
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.16.0/kind-linux-amd64
        chmod +x ./kind
        ./kind delete cluster || true
        docker image prune -f
