on: pull_request
name: Helm Upgrade Tests
jobs:
  test-upgrades:
    runs-on: [self-hosted, ops]
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Setup Kind cluster
        uses: helm/kind-action@v1.5.0

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Install test dependencies
          run: |
            sudo apt-get install -y jq yq

        - name: Run upgrade tests
          run: ./test/run-test-suite.sh
