name: Test Humio Operator
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  test-operator:
    name: ${{ matrix.kind-k8s-version }}
    runs-on: [ self-hosted, ops ]
    strategy:
      fail-fast: false
      matrix:
        kind-k8s-version:
          - kindest/node:v1.29.14@sha256:8703bd94ee24e51b778d5556ae310c6c0fa67d761fae6379c8e0bb480e6fea29 # Not officially supported by kind 0.29.0
          - kindest/node:v1.30.13@sha256:397209b3d947d154f6641f2d0ce8d473732bd91c87d9575ade99049aa33cd648
          - kindest/node:v1.31.9@sha256:b94a3a6c06198d17f59cca8c6f486236fa05e2fb359cbd75dabbfc348a10b211
          - kindest/node:v1.32.5@sha256:e3b2327e3a5ab8c76f5ece68936e4cafaa82edf58486b769727ab0b3b97a5b0d
          - kindest/node:v1.33.1@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.6'
      - name: cleanup kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.29.0/kind-linux-amd64
          chmod +x ./kind
          ./kind delete cluster || true
          make clean
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get temp bin dir
        id: bin_dir
        run: echo "BIN_DIR=$(mktemp -d --tmpdir=${{ github.workspace }})" >> $GITHUB_OUTPUT
      - name: Find latest Humio Core preview docker image
        id: docker_tag
        run: |
          docker pull humio/humio-core:preview
          LATEST_TAG=$(docker run --rm humio/humio-core:preview cat /tag.txt)
          echo "HUMIO_CORE_DEV_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT
      - name: run e2e tests
        env:
          HUMIO_OPERATOR_DEFAULT_HUMIO_CORE_IMAGE: ${{ steps.docker_tag.outputs.HUMIO_CORE_DEV_TAG }}
          BIN_DIR: ${{ steps.bin_dir.outputs.BIN_DIR }}
          HUMIO_E2E_LICENSE: ${{ secrets.HUMIO_E2E_LICENSE }}
          E2E_KIND_K8S_VERSION: ${{ matrix.kind-k8s-version }}
          E2E_LOGS_HUMIO_HOSTNAME: ${{ secrets.E2E_LOGS_HUMIO_HOSTNAME }}
          E2E_LOGS_HUMIO_INGEST_TOKEN: ${{ secrets.E2E_LOGS_HUMIO_INGEST_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GINKGO_NODES: "6"
        run: |
          echo "Running operator tests against humio-core-dev:$HUMIO_CORE_DEV_TAG"
          hack/run-e2e-using-kind.sh
      - name: cleanup kind
        if: always()
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.29.0/kind-linux-amd64
          chmod +x ./kind
          ./kind delete cluster || true
          make clean
          docker image prune -f
          docker buildx prune --all -f
