on:
  push:
    branches:
    - master
    paths:
    - images/helper/version.go
name: Publish Container Helper Image Release
jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get release version
      id: get_version
      run: echo "RELEASE_VERSION=$(grep "Version =" images/helper/version.go | awk -F'"' '{print $2}')" >> $GITHUB_ENV
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker build
      run: make docker-build-helper IMG=humio/humio-operator-helper:${{ env.RELEASE_VERSION }} IMG_BUILD_ARGS="--label version=${{ env.RELEASE_VERSION }} --label release=${{ github.run_id }}"
    - name: docker push
      run: make docker-push IMG=humio/humio-operator-helper:${{ env.RELEASE_VERSION }}
    - name: redhat scan login
      uses: docker/login-action@v1
      with:
        registry: scan.connect.redhat.com
        username: unused
        password: ${{ secrets.RH_SCAN_HUMIO_OPERATOR_HELPER_KEY }}
    - name: redhat scan tag
      env:
        RH_SCAN_OSPID: ${{ secrets.RH_SCAN_HUMIO_OPERATOR_HELPER_OSPID }}
      run: docker tag humio/humio-operator-helper:${{ env.RELEASE_VERSION }} scan.connect.redhat.com/$RH_SCAN_OSPID/humio-operator-helper:${{ env.RELEASE_VERSION }}
    - name: redhat scan push
      env:
        RH_SCAN_OSPID: ${{ secrets.RH_SCAN_HUMIO_OPERATOR_HELPER_OSPID }}
      run: make docker-push IMG=scan.connect.redhat.com/$RH_SCAN_OSPID/humio-operator-helper:${{ env.RELEASE_VERSION }}
