on:
  push:
    branches:
    - master
    paths:
    - images/helper/version.go
name: Publish Container Helper Image Release
jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get release version
      id: get_version
      run: echo ::set-env name=RELEASE_VERSION::$(grep "Version =" images/helper/version.go | awk -F'"' '{print $2}')
    - name: docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run:  echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - name: copy license
      run: cp ./LICENSE images/helper/
    - name: docker build
      run: docker build --label version=${{ env.RELEASE_VERSION }} --label release=${{github.run_id}} -t humio/humio-operator-helper:${{ env.RELEASE_VERSION }} images/helper
    - name: docker push
      run: docker push humio/humio-operator-helper:${{ env.RELEASE_VERSION }}
    - name: redhat scan login
      env:
        RH_SCAN_KEY: ${{ secrets.RH_SCAN_HUMIO_OPERATOR_HELPER_KEY }}
        RH_SCAN_OSPID: ${{ secrets.RH_SCAN_HUMIO_OPERATOR_HELPER_OSPID }}
      run:  echo $RH_SCAN_KEY | docker login -u unused scan.connect.redhat.com --password-stdin
    - name: redhat scan tag
      run: docker tag humio/humio-operator-helper:${{ env.RELEASE_VERSION }} scan.connect.redhat.com/${{ env.RH_SCAN_OSPID }}/humio-operator-helper:${{ env.RELEASE_VERSION }}
    - name: redhat scan push
      run: docker push scan.connect.redhat.com/${{ env.RH_SCAN_OPSID }}/humio-operator-helper:${{ env.RELEASE_VERSION }}

