on:
  push:
    tags:
      - 'v*'
name: Publish Release
jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get release version
      id: get_version
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: operator-sdk
      env:
        GO111MODULE: "on"
      uses: ./.github/action/operator-sdk
      with:
        args: build humio/humio-operator:${{ env.RELEASE_VERSION }}
    - name: docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run:  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: docker push
      run:  docker push humio/humio-operator:${{ env.RELEASE_VERSION }}
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - uses: actions/create-release@latest
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          body: Release ${{ env.RELEASE_VERSION }}
          prerelease: true
