on:
  push:
    tags:
      - 'v*'
name: Publish Release
jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get release version
      id: get_version
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run:  echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - name: operator-sdk build
      env:
        GO111MODULE: "on"
      uses: ./.github/action/operator-sdk
      with:
        args: operator-sdk build humio/humio-operator:${{ env.RELEASE_VERSION }}
    - name: docker push
      run:  docker push humio/humio-operator:${{ env.RELEASE_VERSION }}
    - name: operator-courier push
      env:
        GO111MODULE: "on"
        QUAY_ACCESS_TOKEN: ${{ secrets.QUAY_ACCESS_TOKEN }}
        QUAY_NAMESPACE: ${{ secrets.QUAY_NAMESPACE }}
      uses: ./.github/action/operator-sdk
      with:
        args: operator-courier push deploy/olm-catalog/humio-operator ${{ env.QUAY_NAMESPACE }} humio-operator ${{ env.RELEASE_VERSION }} "$QUAY_ACCESS_TOKEN"
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - uses: actions/create-release@latest
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          body: Release ${{ env.RELEASE_VERSION }}
          prerelease: true
