on:
  push:
    branches:
    - master
    paths:
    - images/helper/version.go
name: Publish Container Helper Image Release
jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set version information
      run: |
        echo "RELEASE_VERSION=$(grep "Version =" images/helper/version.go | awk -F'"' '{print $2}')" >> $GITHUB_ENV
        echo "RELEASE_COMMIT=$(git rev-parse --verify HEAD)" >> $GITHUB_ENV
        echo "RELEASE_DATE=$(date --iso-8601=seconds)" >> $GITHUB_ENV
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker build
      run: make docker-build-helper IMG=humio/humio-operator-helper:${{ env.RELEASE_VERSION }} IMG_BUILD_ARGS="--label version=${{ env.RELEASE_VERSION }} --label release=${{ github.run_id }} --build-arg RELEASE_VERSION=${{ env.RELEASE_VERSION }} --build-arg RELEASE_COMMIT=${{ env.RELEASE_COMMIT }} --build-arg RELEASE_DATE=${{ env.RELEASE_DATE }}"
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install six
    - name: CrowdStrike Container Image Scan Operator Helper
      uses: crowdstrike/container-image-scan-action@v0.7
      with:
        falcon_client_id: 1cd30708cb31442f85a6eec83279fe7b
        container_repository: humio/humio-operator-helper
        container_tag: ${{ env.RELEASE_VERSION }}
      env:
        FALCON_CLIENT_SECRET: "${{ secrets.FALCON_CLIENT_SECRET }}"
    - name: docker push
      run: make docker-push IMG=humio/humio-operator-helper:${{ env.RELEASE_VERSION }}
